### ISSUE TITLE
希望添加按游戏文件夹名称排序功能

### ISSUE THREAD

**Issue by Falleninmemary** [tpunix/SAROO#101]
现在游戏排序挺乱的，希望能添加按游戏文件夹名称排序的功能

**Comment by tzmwx** [comment]
用windows自带剪切粘贴功能即可
https://www.bilibili.com/video/BV1vH4y177UB/?spm_id_from=333.337.search-card.all.click

**Comment by Falleninmemary** [comment]
> 用windows自带剪切粘贴功能即可 https://www.bilibili.com/video/BV1vH4y177UB/?spm_id_from=333.337.search-card.all.click
原来可以这样排序，非常感谢
