### ISSUE TITLE
BIN folder content shown on Select Game

### ISSUE THREAD

**Issue by putifruti** [tpunix/SAROO#103]
Doing a reset after launching some binaries from "Load Binary" option, "Select Game" shows BIN folder contents instead of ISO (and freeze if you launch any binary file)

**Comment by williamdsw** [comment]
Have you tried shutdown and power on Saturn again? I think the Load Binary section it's not quite useful for now... unless you do have the SD Loader application to run internal save backup.

**Comment by putifruti** [comment]
Of course turning off the machine solves the problem. It's just that resetting is faster. Certainly the Load Binary option functionality is limited. I've tested some homebrew with success (240pSuite, SDLoader, and some little games as mine sweeper...) but not many of them come in this format. Anyway, Iso+wav homebrew converted to multitrack bin+cue almost always works
