### ISSUE TITLE
Flash Saroo with PC

### ISSUE THREAD

**Issue by iamaldovanucci** [tpunix/SAROO#111]
Are there any instructions available that detail how to flash the firmware to the Saroo from a PC? I have a bricked cartridge that I would like to fix.

**Comment by williamdsw** [comment]
Turn on automatic subtitles.
https://www.youtube.com/watch?v=WrodY7CBDeI

**Comment by iamaldovanucci** [comment]
Thanks for sharing that link! My SAROO is working again.
