### ISSUE TITLE
Silhouette Mirage glitchy sound

### ISSUE THREAD

**Issue by spooky77777** [tpunix/SAROO#118]
Using Firmware 0.5, Silhouette Mirage still plays without sound effects. 

Has anyone messed around with the sector values and figured out a fix yet?

**Comment by NoName141203** [comment]
I found this setting on the SegaXtreme forums and it worked for me. You should try it

# SILHOUETTEMIRAGE
[T-32901G V1.003]
sector_delay=4000

**Comment by spooky77777** [comment]
> I found this setting on the SegaXtreme forums and it worked for me. You should try it
> 
> [T-32901G V1.003] sector_delay=4000

Tried it just now, with mixed results. There were still no sound effects during the tutorial, then the sound worked perfectly during stage 1, then back to no SFX during stage 2. If it makes a difference, I was using the english patched version.

**Comment by tzmwx** [comment]
sector_delay=5000
play_delay=5000

**Comment by spooky77777** [comment]
> check your CDimage ID 1.??? (1.003 or 1.100）
> 
> [T-32901G V1.???] sector_delay=5000 play_delay=5000

I tried these settings for both 1.003 and 1.100, english-patched & unpatched versions, same result. Sound FX work perfectly for Stage 1, then stop working during Stage 2.

**Comment by tpunix** [comment]
There should be two space between "T-32901G" and "V1.xxx". 
Multiple space only show one when post it on github.

**Comment by spooky77777** [comment]
> There should be two space between "T-32901G" and "V1.xxx". Multiple space only show one when post it on github.

This seems to have done the trick, thanks! Played all the way up to the Dynamis fight, sound was working fine the entire time.

**Comment by evanjosephcode** [comment]
> There should be two space between "T-32901G" and "V1.xxx". Multiple space only show one when post it on github.

is there a reason some configs in the default config file have three spaces and others have 2 (like this one)? 

Thanks for your work
