### ISSUE TITLE
New Feature - Support ROM Cartridges

### ISSUE THREAD

**Issue by filipe-maia** [tpunix/SAROO#12]
Hi.
Don't know if it is possible.
It would be great if it could replace ROM cartridges, like the The King of Fighters '95.
The user would place the ROM image in a folder of the SD Card and SAROO would replace the ROM cartridge.
Thanks.

**Comment by tpunix** [comment]
ROM cartrodges is conflict with saturn firm. Please use YZB's hack version: https://segaxtreme.net/threads/yzbs-4mb-hacks.24601/

**Comment by lzibeti** [comment]
> ROM cartrodges is conflict with saturn firm. Please use YZB's hack version: https://segaxtreme.net/threads/yzbs-4mb-hacks.24601/

I tested with the 2 versions of KOF95 from the link (Normal and AST) and both Saroo behaves as follows:

- Sometimes it asks for the ROM cartridge and gets stuck
- Sometimes it gives a message that the save has been corrupted and then crashes
- Sometimes it loads the game but restarts the device when selecting the characters. If you let the opening appear, it stops at first.
- Sometimes it gets stuck in Saroo, when it is in initial loading.

**Comment by tpunix** [comment]
YZB is work for this.

**Comment by Jungkyu-Lee** [comment]
> > ROM cartrodges is conflict with saturn firm. Please use YZB's hack version: https://segaxtreme.net/threads/yzbs-4mb-hacks.24601/
> 
> I tested with the 2 versions of KOF95 from the link (Normal and AST) and both Saroo behaves as follows:
> 
> * Sometimes it asks for the ROM cartridge and gets stuck
> * Sometimes it gives a message that the save has been corrupted and then crashes
> * Sometimes it loads the game but restarts the device when selecting the characters. If you let the opening appear, it stops at first.
> * Sometimes it gets stuck in Saroo, when it is in initial loading.

I'm experiencing the same thing, is there any way to fix this?
