### ISSUE TITLE
Crash Hang during demo/attract mode

### ISSUE THREAD

**Issue by retrofank** [tpunix/SAROO#126]
Two titles so far have crashed (hang) during it’s demo loop/attract mode.  Seems to be a 100% reproduction rate but occurs after several minutes, roughly after 10 minutes onwards. A hard reset or power off and on is needed afterwards. 

Capcom Generation 5 
Street Fighter Zero 3

My setup
JP NTSC VA10 Saturn
32GB Sandisk Micro SD - FAT32
Redump Bin & Cue disc images.
Firmware is 0.4 (240316 - FPGA 05) not updated to 0.5 yet due to reports of SD card corruption.  

Be good if others could confirm the same and on 0.5, as I have not seen this reported before and those games I mentioned are down as “playable” which they are if you skip the demo mode. 

Thanks

**Comment by Evil-Vegan** [comment]
Hello.

I am unable to replicate this issue on fw0.5 for both games. I ran both of them each through the demonstration loop for thirty minutes.

US NTSC VA1 Saturn
SanDisk 256GB Extreme MicroSDXC UHS-I (exFAT)
Redump BIN/CUE

MCU:240515
SS:240515
FPGA:05

I read a lot of issues here with cards formatted to FAT32. I have had zero issues with my card being formatted to exFAT.

**Comment by retrofank** [comment]
Okay thanks for checking.  I just updated to 0.5 and will run some more tests and if it happens again I’ll try a different SD card and exFAT.


Did you apply the sector delay fix for SFZ3 to address sprite glitches.

**Comment by Evil-Vegan** [comment]
I do not see the sector delay fix added in my configuration file. If that is something you want me to add and test then let me know the information and I will try it.

**Comment by retrofank** [comment]
Config for SFZ3

# STREET FIGHTER ZERO3 (J)
[T-1246G   V1.002]
sector_delay=1000

**Comment by Evil-Vegan** [comment]
Sorry for the late reply to testing! I added the sector delay fix, ran the demonstration again for thirty minutes, and I can say there are zero issues replicated.

**Comment by retrofank** [comment]
New SD card, updated to 0.5 and sector delay fix.  Could not reproduce it again.   Will now close this.
