### ISSUE TITLE
Die Hard Trilogy stopped after the title screen came up 

### ISSUE THREAD

**Issue by lagious** [tpunix/SAROO#139]
Die Hard Trilogy stopped after the title screen came up. 
(The game stops, but soft reset is possible) 
It was the same with JP and US versions, and I haven't tried the PAL version.
I'm using firmware 0.5.

Confusingly, some of my friends who used the same ROM image, the same firmware version, the same kind of SD card, said it working fine. One of them said it didn't work at first, but then it became normal after he deleted the save file. (It didn't work for me) 
Of course, there were people who were in the same situation as me.
It's very unstable.

**Comment by Arnold101knight** [comment]
only to you. game works fine. use redump bin cue

**Comment by TrekkiesUnite118** [comment]
@Arnold101knight 
That's not really how this should be addressed. This is a github issues board, not a reddit or 4chan thread. He clearly said he's using the same ROM image that did work for others. So the image may not be the issue here.

@lagious What image was being used?

**Comment by lagious** [comment]
@TrekkiesUnite118 
At first, I used Redump Sega Saturn's from the Internet Archive. Other than that, I tried two different images, but it turned out the same.

**Comment by TrekkiesUnite118** [comment]
Try cleaning the cart to make sure that's not the issue. If that doesn't work then it probably needs looked at by the devs.

**Comment by lagious** [comment]
@TrekkiesUnite118
I've tried cleaning with isopropyl alcohol, but nothing has changed. (Additionally, out of the 102 games I have, only this one doesn't work normally.)

I think this is similar to the following issues.
[https://github.com/tpunix/SAROO/issues/137](url)

There was an opinion that it was an issue of load & save, and I have the same doubts. Because, one of my friends said that when he erased the existing save files (SS_MEMS.bin, SS_SAVE.bin) and restarted it, it worked fine.
(Unfortunately, I tried to delete the save file several times, but it didn't get any results.)

**Comment by tzmwx** [comment]
> Die Hard Trilogy stopped after the title screen came up. (The game stops, but soft reset is possible) It was the same with JP and US versions, and I haven't tried the PAL version. I'm using firmware 0.5.
> 
> Confusingly, some of my friends who used the same ROM image, the same firmware version, the same kind of SD card, said it working fine. One of them said it didn't work at first, but then it became normal after he deleted the save file. (It didn't work for me) Of course, there were people who were in the same situation as me. It's very unstable.



Take a picture of the interface of the SAROO main menu and show me the information at the bottom of your screen

**Comment by lagious** [comment]
@tzmwx 

![20240616_161316](https://github.com/tpunix/SAROO/assets/172553015/3b57a318-3408-4094-9153-008723d51384)

[saroocfg.txt](https://github.com/user-attachments/files/15856496/saroocfg.txt)

Should I upload save files?

**Comment by Arnold101knight** [comment]
> @Arnold101knight That's not really how this should be addressed. This is a github issues board, not a reddit or 4chan thread. He clearly said he's using the same ROM image that did work for others. So the image may not be the issue here.
> 
> @lagious What image was being used?

as i said before, shut up clown.

I have misreaded Alien trilogy instead of die hard because was very tired, sorry lagious

**Comment by tzmwx** [comment]
> @tzmwx
> 
> ![20240616_161316](https://private-user-images.githubusercontent.com/172553015/340071845-3b57a318-3408-4094-9153-008723d51384.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2ODQ5OTEsIm5iZiI6MTcxODY4NDY5MSwicGF0aCI6Ii8xNzI1NTMwMTUvMzQwMDcxODQ1LTNiNTdhMzE4LTM0MDgtNDA5NC05MTUzLTAwODcyM2Q1MTM4NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQwNDI0NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDI1Y2RmYzIxZjE4ZDU2N2VlYjA0MzFmNWNlYTZlMzJhZDBhNDI3YmU0YzI3NmNkZDQwOWVjMWJjYTQ3NjY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UO-MKxQDq0Rcg5WPSvYLsyhDEP_t4df23x0T66dBS3I)
> 
> [saroocfg.txt](https://github.com/user-attachments/files/15856496/saroocfg.txt)
> 
> Should I upload save files?

OK
Can you post some photos of the saroo? The motherboard and the U6 chip (the memory chip in the upper left corner)

**Comment by lagious** [comment]
@tzmwx 

![20240618_134008](https://github.com/tpunix/SAROO/assets/172553015/6be7a73c-9394-4f68-8c37-43b87f61d00e)
![20240618_133925](https://github.com/tpunix/SAROO/assets/172553015/922d2709-b29d-42f4-8915-1d1068757e13)

Here you are

**Comment by tzmwx** [comment]
> @tzmwx
> 
> ![20240618_134008](https://private-user-images.githubusercontent.com/172553015/340541730-6be7a73c-9394-4f68-8c37-43b87f61d00e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2ODYzNzYsIm5iZiI6MTcxODY4NjA3NiwicGF0aCI6Ii8xNzI1NTMwMTUvMzQwNTQxNzMwLTZiZTdhNzNjLTkzOTQtNGY2OC04YzM3LTQzYjg3ZjYxZDAwZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQwNDQ3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGE3YTMwNTlhMDJjNGVmNWU5NzExMjgxMjM1MzczOGIzYTY0YjRhZTk3Y2RmZWI5NjlhNWU3N2UyYTJiZWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UwKKtEVaqs5I9M8CrpENcSBUfwD_8CnA_uSvdG2Wah4) ![20240618_133925](https://private-user-images.githubusercontent.com/172553015/340541755-922d2709-b29d-42f4-8915-1d1068757e13.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2ODYzNzYsIm5iZiI6MTcxODY4NjA3NiwicGF0aCI6Ii8xNzI1NTMwMTUvMzQwNTQxNzU1LTkyMmQyNzA5LWIyOWQtNDJmNC04OTE1LTFkMTA2ODc1N2UxMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQwNDQ3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTIzY2U0NDI2N2RiZWZkNDE5M2UyNTc4ZGVjYzA2MTIxNmUwOGUwYTRiMzk2YzVmM2I0NGJlMWIzNjU4NTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LsBXJ10L3vj5jvCLMebXChUhclbuwHy1niEqc9nLr9c)
> 
> Here you are

There seem to be two versions of saroo on this motherboard. What version did you purchase?

**Comment by lagious** [comment]
@tzmwx 

Are you asking if it's an elite or normal version? It's an elite version (using a new chip)

**Comment by tzmwx** [comment]
> @tzmwx
> 
> Are you asking if it's an elite or normal version? It's an elite version (using a new chip)
> 
> If you mean the circuit version, it is written as version 1.6.

The photo is clear, but the printed font is blurry.

 OK, test it with the following cfg file
[saroocfg.txt](https://github.com/user-attachments/files/15880856/saroocfg.txt)

**Comment by lagious** [comment]
@tzmwx 

No change. I've tried erasing the save files, but it's the same result.

**Comment by tzmwx** [comment]
> @tzmwx
> 
> No change. I've tried erasing the save files, but it's the same result.

1Use the cfg file I provided 
2Post the file structure diagram of your JP version 
3Shoot a video of where it is stuck 
4Upload your image cue file

**Comment by lagious** [comment]
@tzmwx 

Okay, but I'm not sure what No.2 means, can you explain it easily?

**Comment by tzmwx** [comment]
> @tzmwx
> 
> No change. I've tried erasing the save files, but it's the same result.

You need to copy and paste the contents of the above file into your cfg file or directly test it again with the following file
Test again
[saroocfg.txt](https://github.com/user-attachments/files/15881304/saroocfg.txt)

**Comment by tzmwx** [comment]
This is the result of YZB tracking，It belongs to a bug in this game that may occur in certain specific situations. After the next version of the saoo software is released, you can delete the relevant content in the cfg file
