### ISSUE TITLE
sega ages I love mickey mouse (japan)

### ISSUE THREAD

**Issue by enso1189** [tpunix/SAROO#148]
When I select a game, the screen freezes.

**Comment by lagious** [comment]
Shorten the name of the folder that contains the rom image. It's a problem because the default name is too long.

**Comment by yzbss** [comment]
I tested on version 0.5v firmware, using folders with long filenames as well as files, and selected any of the games worked without any problems
![1](https://github.com/tpunix/SAROO/assets/173325971/28796ee8-4b4a-44f3-807c-409c73269069)

**Comment by lagious** [comment]
@yzbss 

Maybe it's a difference depending on whether or not using the category command.
I'm using it.

**Comment by yzbss** [comment]
You are right, maybe the next version will fix this problem

**Comment by lagious** [comment]
@yzbss 

Sorry for erasing my comment. I accidentally deleted it while trying to correct it.
