### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by RangerKoc** [tpunix/SAROO#15]
```
char *lang_ru[LANG_STR_NR] = {
  "Выбор игры (%d/%d)",
  "Выбор файла (%d/%d)",
  "Запуск игры ...",
  "Сбой запуска игры! %d",
  "Запуск файла ...",
  "Сбой запуска файла! %d",
  "Выбрать игру",
  "Системный CD проигрыватель",
  "Запустить игру с диска",
  "Инструмент отладки",
  "Запустить исп. файл",
  "Обновление ПО",
  "Обновление, не отключайте питание ...",
  "Сбой обновления!",
  "Обновление завершено, требуется перезапуск!",
  "Основное меню SAROO",
};
```

**Comment by cyo-the-vile** [comment]
You need to lower the charecter count. There is a limitation

**Comment by RangerKoc** [comment]
char *lang_ru[LANG_STR_NR] = {
  "Выбор игры (%d/%d)",
  "Выбор файла (%d/%d)",
  "Запуск игры ...",
  "Сбой запуска игры! %d",
  "Запуск файла ...",
  "Сбой запуска файла! %d",
  "Выбрать игру",
  "Системный CD плеер",
  "Запустить игру с диска",
  "Инструмент отладки",
  "Запустить исп. файл",
  "Обновление ПО",
  "Обновление, не отключайте ...",
  "Сбой обновления!",
  "Обновлено! требуется перезапуск!",
  "Основное меню SAROO",
};

**Comment by xvortex** [comment]
> I have a question: where I can get a sh-elf-gcc toolchain?

Here we go: http://www.rockin-b.de/windows-saturnorbit.html
(in Resources section)

**Comment by xvortex** [comment]
> char *lang_ru[LANG_STR_NR] = {

Я внедрил твой перевод у себя в [репо](https://github.com/xvortex/SAROO). Параллельно изменил шрифт и переделал его вывод, т.к. оригинальный русский шрифт это ужас.

**Comment by LobAnovich** [comment]
> > char *lang_ru[LANG_STR_NR] = {
> 
> Я внедрил твой перевод у себя в [репо](https://github.com/xvortex/SAROO). Параллельно изменил шрифт и переделал его вывод, т.к. оригинальный русский шрифт это ужас.

Приветствую ! "Правильный" продавец с Али предлагает к установке на свои свежепроданые флешкарики прошивку от 25/11/23. Которая лежит на странице его гугл хранилища. Я не знаю,можно ли размещать ссылки на персональные страницы чужих хранилищ. Но вновь купленный картридж не захотел обновлятся ни с этого,ни с вашего репозитория. Только по ссылке от продавца

 
![index](https://github.com/tpunix/SAROO/assets/113496444/084c61db-1c8b-4ba5-857f-3a5a74174050)

Можно будет
прикрутить к этой прошивке меню на русском языке ?

**Comment by LobAnovich** [comment]
[SAROO_25_11_23.zip](https://github.com/tpunix/SAROO/files/13763726/SAROO_25_11_23.zip)
