### ISSUE TITLE
Pandemonium! (USA)

### ISSUE THREAD

**Issue by keeper7keys** [tpunix/SAROO#155]
Tested on FW: 0.4, 0.5 and 0.6

This game suffers from audio distortion on some levels especially on level 14:
https://youtu.be/3A2z2SLtMcQ

https://youtu.be/nUCUmW2rfPE

An easy way to test this game is using invincibility code and a password to level 14.
At the password option type HARDBODY for invincibility and then type FEIIAMGE.
When the game starts press left on the map and choose level 14.
In the beginning of the level 14 the audio is normal but it gets distorted always at the same locations (video above).

Regards

**Comment by tzmwx** [comment]
How do I enter the code above? The code I entered is invalid.

Do you know the specific model of your SATURN?

**Comment by goukizero** [comment]
Many games with audio problems are repaired with the txt fix. I'll try and let you know.

**Comment by Mikeylovesretro** [comment]
Okay, so I'm on Firm V0.6 and have no issues with the game. Entered the codes as instructed and no audio issues all. Play perfectly fine.

**Comment by goukizero** [comment]
Now it loads very slowly, like originally, we would have to try to regulate it
sector_delay=2000
play_delay=4000

This is a test, I don't know how it will turn out.
Can you try it and comment? thank you

**Comment by keeper7keys** [comment]
> How do I enter the code above? The code I entered is invalid.
> 
> Do you know the specific model of your SATURN?

Enter the code at the password screen. After you enter HARDBODY a message will show "CAN'T TOUCH THIS" or something like that. Then replace HARDBODY with the stage password FEIIAMGE.

I have a US Saturn model 1 and a white japanese model 2.

**Comment by keeper7keys** [comment]
> Okay, so I'm on Firm V0.6 and have no issues with the game. Entered the codes as instructed and no audio issues all. Play perfectly fine.

Did you test it using the config settings above or without anything?

**Comment by keeper7keys** [comment]
> Many games with audio problems are repaired with the txt fix. I'll try and let you know.
> 
> Try this, it will make the game load at the original CD speed and we can know if "adjusting" will work well
> 
> (# ) Pandemonium! (USA) [T-15914H V1.001] sector_delay=8000 play_delay=30000
> 
> Remove () and in front of pandemoniun, otherwise the forum puts things in capital letters and bold xd

I'm far away from my home now.
I will test as soon as I can.
Thanks

**Comment by Mikeylovesretro** [comment]
> > Okay, so I'm on Firm V0.6 and have no issues with the game. Entered the codes as instructed and no audio issues all. Play perfectly fine.
> 
> Did you test it using the config settings above or without anything?

Without. No changes to the config. Might want to try a different ISO file. I got mine from Cdromance

**Comment by goukizero** [comment]
The isos are generally fine, in my txt I have fixes for more than 40 games. Without configuration many games fail and changing the iso doesn't solve anything

**Comment by Mikeylovesretro** [comment]
> The isos are generally fine, in my txt I have fixes for more than 40 games. Without configuration many games fail and changing the iso doesn't solve anything

Is it possible to share this txt file?

**Comment by goukizero** [comment]
[Arreglos Juegos Alfabeticamente.0.6.txt](https://github.com/user-attachments/files/16085538/Arreglos.Juegos.Alfabeticamente.0.6.txt)

There you have, are the arrangements that need to be made and also all multidisc games at least in one region.
Please keep in mind that if your version of the game does not match the txt version, the fix will not work.
I always try to use the newest redump iso

**Comment by keeper7keys** [comment]
I did test with some config settings variations but the audio still glitches.
The ISO I have is the same from cdromance.
PS: The audio always glitches at the same spot meaning the exact same locations I recorded.

**Comment by goukizero** [comment]
archive.org, redump 20224

**Comment by keeper7keys** [comment]
There's nothing wrong with the ISO.
I did a hex comparison. It's the same.

**Comment by Mikeylovesretro** [comment]
@keeper7keys just curious the saroo is the normal or elite version and is your SD card format exfat or fat32?

Also, have you tried using a different SD card as sometimes SD cards can be finicky

**Comment by keeper7keys** [comment]
@Mikeylovesretro 
It's from retroparadise.
Original SD card Class 10 Sandisk.
Did you finish the level 14 or just play the beginning?

**Comment by Mikeylovesretro** [comment]
> @Mikeylovesretro It's from retroparadise. (not refurbished parts) Original SD card Class 10 Sandisk. Did you finish the level 14 or just play the beginning?

Yes, I played the whole level and beat the game as well.

So this is an Elite board which I believe is a blue circuit board

Is the card formatted in exfat or Fat32
Have you tried a different SD Card with just that game on it

Please let us know so we may isolate the issue

**Comment by keeper7keys** [comment]
It would be good if someone else could test this game because I highly doubt that a cluster size or file system could cause this issue.

**Comment by Mikeylovesretro** [comment]
> It would be good if someone else could test this game because I highly doubt that a cluster size or file system could cause this issue.

As you directed, I already tested the game with the passwords played the level, and beat the game. So if you are not going to answer questions then please don't waste people's time. I asked you twice the following questions and yet you asking others to test the game.

**Comment by lagious** [comment]
It seems like a bug in the game itself, not a problem with Saroo.

https://www.reddit.com/r/SegaSaturn/comments/rqn8k9/pandemonium_on_sega_saturn/

**Comment by keeper7keys** [comment]
@lagious
Thanks for the link. 
Very interesting to know that this is a game issue.

PS: Now we know who was wasting other people's time.
