### ISSUE TITLE
Resident Evil (USA) and Biohazard (Japan)

### ISSUE THREAD

**Issue by keeper7keys** [tpunix/SAROO#16]
The game freezes when you try to use Umbrella Lab computer.
https://i.imgur.com/GKMVbAC.jpg

During this part of the game the following delay sets were used:
sector_delay=2000, sector_delay=1000, sector_delay=1100 and sector_delay=500

Credit for the test:
Pancada Plays on YouTube.

**Comment by tpunix** [comment]
Please post a save here.  Real save or emulator save.

**Comment by keeper7keys** [comment]
It's a save from emulator. It is near the Lab computer.
[https://mega.nz/file/mhg3XLQC#tlMy6IXAiGQbGN7AlGm1uC44NYQD5dgFbrpZGHEv5Kw](url)

**Comment by keeper7keys** [comment]
There are saves for Resident Evil (USA) and Biohazard (J).
You will start near the computer lab room.
The game freezing seems to occur randomly in both games.

Saroo's SS_SAVE.BIN:
https://mega.nz/file/W4xiQKqY#XGzdbOikBCKYnbRCWIJg5_3yVmXL7JZinLXRAWMwVdA

**Comment by keeper7keys** [comment]
> Please post a save here. Real save or emulator save.

There are save files for Resident Evil (USA) and Biohazard (J) in the link below.
You will start near the computer lab room.
The game freezing seems to occur randomly.

Saroo's SS_SAVE.BIN:
https://mega.nz/file/W4xiQKqY#XGzdbOikBCKYnbRCWIJg5_3yVmXL7JZinLXRAWMwVdA
