### ISSUE TITLE
CROC LEGEND OF THE GOBBOS GRAPHICAL ISSUES

### ISSUE THREAD

**Issue by VinCLTU** [tpunix/SAROO#163]
T-5029H-50V1.000     ROM

saroo latest version , software 0.6 , sd card came factory with saroo , the game works with graphical artefacts i have no idea how to fix it .

**Comment by goukizero** [comment]
croc is a game with a documented house bug. of my 3 consoles in the pal model 2 with bios ver 1.01 has the errors, it is a problem that occurs with the original game in certain bios

**Comment by VinCLTU** [comment]
I got Saturn model 2 PAL-C-V1,01a bios i think i found solution how to play CROC with no graphic issues : first i load the game from Saroo boot menu , then i press (A) (B) (C) + (START) buttons at the same time and hold till it loads CD Player screen with options , there i move to the upper left icon with saturn logo that says Start Application and press (A) button to start the game , and it loads fine with no visual glitch.
