### ISSUE TITLE
No return to Saroo menu after „ABC + START“

### ISSUE THREAD

**Issue by Bomberman94** [tpunix/SAROO#165]
FW v0.6 with Japanese Sega Saturn Victor

ABC + START will exit a game and return to the Saturn CD menu but no joystick combination will bring me to the Saroo menu.

**Comment by tzmwx** [comment]
pressing START button

**Comment by Bomberman94** [comment]
> pressing START button

… won’t work. You can see and hear that Start is pressed (jumping Saturn „S“) but nothing else happens. Maybe I made something wrong: I formatted a 128 GB SanDisk Card with exFat and copied the 0.6 Firmware and some games (yes, correct names and folders). Do I lack some files or is my Saturn „special“ (no battery cell in the Saturn but a VCD Card inserted).

**Comment by Bomberman94** [comment]
… should I make a video of it?

**Comment by tzmwx** [comment]
1. Shoot a video，upload it.
2.What is the BIOS version of your Saturn？
3. You can plug and unplug the cartridge multiple times to see if it can improve

**Comment by Bomberman94** [comment]
Here‘s a video of it:

https://youtu.be/nHlFiQBPUgk?si=duAjbZk-ildgTFOo

The Bios of my Victor Sega Saturn is V1.00 (I think there is a newer one around - 1.01 or so). Unmodded without battery cell (therefore the message at the beginning) and an original VCD cart inserted. 

Here is a picture of my Saturn:

https://postimg.cc/mcK94Fjf

And I tried it many many times with re-inserting the cartridge but it never worked with getting back tongue Saroo menu.

**Comment by tzmwx** [comment]
We learned for the first time that there is still jvc BIOS 1.00, and we have just obtained this version.

 waiting for an update from TPU

**Comment by Bomberman94** [comment]
… I can test the update if he wants to. 😊

**Comment by tonyhoro** [comment]
ABC+Start is not corrupting save/files anymore (at least for an hour I spent testing) on V.0.6 but the reset function is indeed going back to the game instead of the Saroo Menu.

Also, I don't know if I should open a different topic about this, but the FW version isn't appear at the bottom of the menu anymore.

**Comment by unknown2918** [comment]
Same problem occurs with Samsung Saturn.
The bios version is 1.02a
The site below provides information on the BIOS.

https://segaretro.org/Sega_Saturn/Boot_ROM

**Comment by unknown2918** [comment]
> 우리는 처음으로 jvc BIOS 1.00이 아직 존재한다는 사실을 알게 되었고, 이 버전을 방금 얻었습니다.
> 
> TPU 업데이트를 기다리는 중

삼성 새턴에서도 같은 문제가 발생합니다.
바이오스 버전은 1.02a입니다.
아래 사이트는 BIOS에 대한 정보를 제공합니다.

https://segaretro.org/Sega_Saturn/Boot_ROM

**Comment by unknown2918** [comment]
> We learned for the first time that there is still jvc BIOS 1.00, and we have just obtained this version.
> 
> waiting for an update from TPU

I have the same problem with my Samsung Saturn.
The BIOS version is 1.02a.
The site below provides information on the BIOS.

https://segaretro.org/Sega_Saturn/Boot_ROM

**Comment by neodkl** [comment]
Good day all,
I have exactly the same problem using Saroo (lateste firmware) with my Japanese Saturn (bios v1.00). Has a solution been found by any chance? 
Thanks

**Comment by Bomberman94** [comment]
Will this be fixed in a later version or should I buy a Saturn with Bios > 1.0 ? 🤔

**Comment by Bomberman94** [comment]
Does it work with V-Saturn with Bios V1.01 - anyone knows? Thanks

**Comment by tzmwx** [comment]
The next version of the software will support jvc1.00 BIOS

**Comment by Bomberman94** [comment]
FW 0.7 fixed this problem - only Tryrush Deppy returns into game (and NOT Saroo menu) after pressing START.

Thank you for the fix!
