### ISSUE TITLE
Saroo Crashing after starting

### ISSUE THREAD

**Issue by carlosmagnu** [tpunix/SAROO#169]
Dear, I would like you to be able to help me resolve this annoying problem. Saroo starts, however, after selecting the game it does not load and crashes.
![WhatsApp Image 2024-07-19 at 17 25 19](https://github.com/user-attachments/assets/8cb79a9c-d393-4c3b-9271-433b1a2c0f08)

**Comment by tzmwx** [comment]
Your image is incorrect, please replace the image

**Comment by carlosmagnu** [comment]
Dear, Adm. I verified that after unzipping the rom they were in a subfolder structure. This made the saroo display the game, but prevented the system from loading the game properly, causing the crash. I leave the suggestion to friends who can check if the game files are in just one folder. If there is a subfolder structure with the files, you must fix this to enjoy the product. Hope this helps!

**Comment by Retro-Nerd** [comment]
tzmwx meant that you probably tried to load a somewhat broken CD Image. Try CD Images from the Redump collection first.

**Comment by williamdsw** [comment]
> Dear, Adm. I verified that after unzipping the rom they were in a subfolder structure. This made the saroo display the game, but prevented the system from loading the game properly, causing the crash. I leave the suggestion to friends who can check if the game files are in just one folder. If there is a subfolder structure with the files, you must fix this to enjoy the product. Hope this helps!

You can try to run this image I made since, homebrews you need to convert original image to bin/cue with daemon tools + ultra ISO:
https://drive.google.com/file/d/13CNbI9kqb65enEVV6u9CCVaoOLdclMrT/view?usp=sharing

**Comment by tzmwx** [comment]
runs fine
V0.1.1（https://www.segasaturnshiro.com/2024/01/05/x-men-arcade-being-ported-to-saturn/）

What version are you using?

**Comment by tzmwx** [comment]
V0.2.0
（https://www.segasaturnshiro.com/2024/03/29/new-version-of-x-men-on-saturn-adds-playable-storm-three-player-co-op/）
![IMG_7082](https://github.com/user-attachments/assets/c37e6775-f3cd-4b38-83a7-a838faa37923)

**Comment by tzmwx** [comment]
> > V 0.2.0 https://www.segasaturnshiro.com/2024/03/29/new-version-of-x-men-on-saturn-adds-playable-storm-three-player-co-op/ ![IMG_7082](https://private-user-images.githubusercontent.com/129564095/350896293-c37e6775-f3cd-4b38-83a7-a838faa37923.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2OTU1MTEsIm5iZiI6MTcyMTY5NTIxMSwicGF0aCI6Ii8xMjk1NjQwOTUvMzUwODk2MjkzLWMzN2U2Nzc1LWYzY2QtNGIzOC04M2E3LWE4MzhmYWEzNzkyMy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMDA0MDExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTNiNjc0YTQ2ZDY4NDliNThkY2MzMjdjNjkyNjE5OGRlMTYwYTNlYzliYjI2NDBmOGYyMmJlOWZlMDMyNmExYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.93FH7k_6BOhmLuvLIxwRScV3UDsGm2HY1tTXVoyCdNo)
> > V 0.2.0 cue file is not compatible, download the cue file here to replace it [game.zip](https://github.com/user-attachments/files/16330592/game.zip)
> 
> There is nothing wrong with the included cue file with V 0.2.0. If Saroo really needs an extra empty space between every line in order to parse a cue sheet properly then there's a bug in it's cue sheet parsing logic that needs to be fixed.

SAROO到今天为止只说过支持ISO和CUE/BIN，还没有正式支持CUE/WAV，所以这不是bug，是SAROO未来的功能，它目前不理解这个CUE文件，卡住了。这个就像这段文字对于你来说需要翻译软件一样，只有将未知的文字转换为你已知的文字，你才能理解。我上传了一个转换过的CUE文件，暂时让SAROO能够运行这个镜像，但实际这个cue文件也是“不规范的”，考虑到既然有玩家想运行这个镜像，为减少重新下载镜像或转换镜像的过程，暂时先下载我提供的cue小文件凑活用吧！


小知识：
SAROO如果遇到运行镜像后在SAROO菜单卡住的，100%是SAROO不支持这个镜像格式。可通过重新转换或修改CUE文件得到改善。建议一般玩家使用“虚拟光驱软件”和Ultra ISO软件重新获取CUE/BIN文件

**Comment by TrekkiesUnite118** [comment]
> > > V 0.2.0 https://www.segasaturnshiro.com/2024/03/29/new-version-of-x-men-on-saturn-adds-playable-storm-three-player-co-op/ ![IMG_7082](https://private-user-images.githubusercontent.com/129564095/350896293-c37e6775-f3cd-4b38-83a7-a838faa37923.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2OTU1MTEsIm5iZiI6MTcyMTY5NTIxMSwicGF0aCI6Ii8xMjk1NjQwOTUvMzUwODk2MjkzLWMzN2U2Nzc1LWYzY2QtNGIzOC04M2E3LWE4MzhmYWEzNzkyMy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMDA0MDExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTNiNjc0YTQ2ZDY4NDliNThkY2MzMjdjNjkyNjE5OGRlMTYwYTNlYzliYjI2NDBmOGYyMmJlOWZlMDMyNmExYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.93FH7k_6BOhmLuvLIxwRScV3UDsGm2HY1tTXVoyCdNo)
> > > V 0.2.0 cue file is not compatible, download the cue file here to replace it [game.zip](https://github.com/user-attachments/files/16330592/game.zip)
> > 
> > 
> > There is nothing wrong with the included cue file with V 0.2.0. If Saroo really needs an extra empty space between every line in order to parse a cue sheet properly then there's a bug in it's cue sheet parsing logic that needs to be fixed.
> 
> SAROO到今天为止只说过支持ISO和CUE/BIN，还没有正式支持CUE/WAV，所以这不是bug，是SAROO未来的功能，它目前不理解这个CUE文件，卡住了。这个就像这段文字对于你来说需要翻译软件一样，只有将未知的文字转换为你已知的文字，你才能理解。我上传了一个转换过的CUE文件，暂时让SAROO能够运行这个镜像，但实际这个cue文件也是“不规范的”，考虑到既然有玩家想运行这个镜像，为减少重新下载镜像或转换镜像的过程，暂时先下载我提供的cue小文件凑活用吧！
> 
> 小知识： SAROO如果遇到运行镜像后在SAROO菜单卡住的，100%是SAROO不支持这个镜像格式。可通过重新转换或修改CUE文件得到改善。建议一般玩家使用“虚拟光驱软件”和Ultra ISO软件重新获取CUE/BIN文件

Again I don't have an issue with Saroo being a work in progress and adding support for new images in the future. I simply don't like when I see you going around claiming a cue sheet is invalid or wrong when there's nothing wrong with it. It makes people think it's a problem with the image the homebrew developer made when that's not the case. The reality is simply that saroo doesn't support ISO/CUE and ISO/CUE/WAV currently. So just say that and tell people they need to convert their images over to BIN/CUE.

Secondly the cue sheet you've provided hasn't really made any changes other than double spacing the entire document. So how does that fix the problem? Does it just make the game boot without any CD audio because Saroo doesn't parse the rest of the cue sheet? If so that's not really a desirable solution. If the CD audio does work and Saroo actually requires that kind of spacing then I'd argue that's wrong as it should be able to read the file properly.

**Comment by tzmwx** [comment]
> > > > V 0.2.0 https://www.segasaturnshiro.com/2024/03/29/new-version-of-x-men-on-saturn-adds-playable-storm-three-player-co-op/ ![IMG_7082](https://private-user-images.githubusercontent.com/129564095/350896293-c37e6775-f3cd-4b38-83a7-a838faa37923.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2OTU1MTEsIm5iZiI6MTcyMTY5NTIxMSwicGF0aCI6Ii8xMjk1NjQwOTUvMzUwODk2MjkzLWMzN2U2Nzc1LWYzY2QtNGIzOC04M2E3LWE4MzhmYWEzNzkyMy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMDA0MDExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTNiNjc0YTQ2ZDY4NDliNThkY2MzMjdjNjkyNjE5OGRlMTYwYTNlYzliYjI2NDBmOGYyMmJlOWZlMDMyNmExYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.93FH7k_6BOhmLuvLIxwRScV3UDsGm2HY1tTXVoyCdNo)
> > > > V 0.2.0 cue file is not compatible, download the cue file here to replace it [game.zip](https://github.com/user-attachments/files/16330592/game.zip)
> > > 
> > > 
> > > There is nothing wrong with the included cue file with V 0.2.0. If Saroo really needs an extra empty space between every line in order to parse a cue sheet properly then there's a bug in it's cue sheet parsing logic that needs to be fixed.
> > 
> > 
> > SAROO到今天为止只说过支持ISO和CUE/BIN，还没有正式支持CUE/WAV，所以这不是bug，是SAROO未来的功能，它目前不理解这个CUE文件，卡住了。这个就像这段文字对于你来说需要翻译软件一样，只有将未知的文字转换为你已知的文字，你才能理解。我上传了一个转换过的CUE文件，暂时让SAROO能够运行这个镜像，但实际这个cue文件也是“不规范的”，考虑到既然有玩家想运行这个镜像，为减少重新下载镜像或转换镜像的过程，暂时先下载我提供的cue小文件凑活用吧！
> > 小知识： SAROO如果遇到运行镜像后在SAROO菜单卡住的，100%是SAROO不支持这个镜像格式。可通过重新转换或修改CUE文件得到改善。建议一般玩家使用“虚拟光驱软件”和Ultra ISO软件重新获取CUE/BIN文件
> 
> Again I don't have an issue with Saroo being a work in progress and adding support for new images in the future. I simply don't like when I see you going around claiming a cue sheet is invalid or wrong when there's nothing wrong with it. It makes people think it's a problem with the image the homebrew developer made when that's not the case. The reality is simply that saroo doesn't support ISO/CUE and ISO/CUE/WAV currently. So just say that and tell people they need to convert their images over to BIN/CUE.
> 
> Secondly the cue sheet you've provided hasn't really made any changes other than double spacing the entire document. So how does that fix the problem? Does it just make the game boot without any CD audio because Saroo doesn't parse the rest of the cue sheet? If so that's not really a desirable solution. If the CD audio does work and Saroo actually requires that kind of spacing then I'd argue that's wrong as it should be able to read the file properly.

![IMG_7099](https://github.com/user-attachments/assets/ba94d02f-a62e-4538-9242-c896e2037c16)
![IMG_7098](https://github.com/user-attachments/assets/3a2fe618-865b-48f3-a461-2fd27ea1e14e)
![IMG_7095](https://github.com/user-attachments/assets/7be3d440-3ae4-42be-b21d-bc3e514f1a23)
![IMG_7094](https://github.com/user-attachments/assets/dd67d409-fc59-4805-9d46-ef1b111b4a27)

**Comment by TrekkiesUnite118** [comment]
> > > > > V 0.2.0 https://www.segasaturnshiro.com/2024/03/29/new-version-of-x-men-on-saturn-adds-playable-storm-three-player-co-op/ ![IMG_7082](https://private-user-images.githubusercontent.com/129564095/350896293-c37e6775-f3cd-4b38-83a7-a838faa37923.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2OTU1MTEsIm5iZiI6MTcyMTY5NTIxMSwicGF0aCI6Ii8xMjk1NjQwOTUvMzUwODk2MjkzLWMzN2U2Nzc1LWYzY2QtNGIzOC04M2E3LWE4MzhmYWEzNzkyMy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMDA0MDExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTNiNjc0YTQ2ZDY4NDliNThkY2MzMjdjNjkyNjE5OGRlMTYwYTNlYzliYjI2NDBmOGYyMmJlOWZlMDMyNmExYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.93FH7k_6BOhmLuvLIxwRScV3UDsGm2HY1tTXVoyCdNo)
> > > > > V 0.2.0 cue file is not compatible, download the cue file here to replace it [game.zip](https://github.com/user-attachments/files/16330592/game.zip)
> > > > 
> > > > 
> > > > There is nothing wrong with the included cue file with V 0.2.0. If Saroo really needs an extra empty space between every line in order to parse a cue sheet properly then there's a bug in it's cue sheet parsing logic that needs to be fixed.
> > > 
> > > 
> > > SAROO到今天为止只说过支持ISO和CUE/BIN，还没有正式支持CUE/WAV，所以这不是bug，是SAROO未来的功能，它目前不理解这个CUE文件，卡住了。这个就像这段文字对于你来说需要翻译软件一样，只有将未知的文字转换为你已知的文字，你才能理解。我上传了一个转换过的CUE文件，暂时让SAROO能够运行这个镜像，但实际这个cue文件也是“不规范的”，考虑到既然有玩家想运行这个镜像，为减少重新下载镜像或转换镜像的过程，暂时先下载我提供的cue小文件凑活用吧！
> > > 小知识： SAROO如果遇到运行镜像后在SAROO菜单卡住的，100%是SAROO不支持这个镜像格式。可通过重新转换或修改CUE文件得到改善。建议一般玩家使用“虚拟光驱软件”和Ultra ISO软件重新获取CUE/BIN文件
> > 
> > 
> > Again I don't have an issue with Saroo being a work in progress and adding support for new images in the future. I simply don't like when I see you going around claiming a cue sheet is invalid or wrong when there's nothing wrong with it. It makes people think it's a problem with the image the homebrew developer made when that's not the case. The reality is simply that saroo doesn't support ISO/CUE and ISO/CUE/WAV currently. So just say that and tell people they need to convert their images over to BIN/CUE.
> > Secondly the cue sheet you've provided hasn't really made any changes other than double spacing the entire document. So how does that fix the problem? Does it just make the game boot without any CD audio because Saroo doesn't parse the rest of the cue sheet? If so that's not really a desirable solution. If the CD audio does work and Saroo actually requires that kind of spacing then I'd argue that's wrong as it should be able to read the file properly.
> 
> ![IMG_7099](https://private-user-images.githubusercontent.com/129564095/351680536-ba94d02f-a62e-4538-9242-c896e2037c16.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzI5NDksIm5iZiI6MTcyMTgzMjY0OSwicGF0aCI6Ii8xMjk1NjQwOTUvMzUxNjgwNTM2LWJhOTRkMDJmLWE2MmUtNDUzOC05MjQyLWM4OTZlMjAzN2MxNi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjRUMTQ1MDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTVlMjI2YjllNDI1YzA5NmQ4OTRiZTdjMzVhY2RhZWQzZjRjZDRmNTlkMGRmM2NiZWY1ZGMxMTA3ODUyN2NjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-h7fnZNaH4mE5aHC8jg5xH5mYzaDydkk6yQjK_zaUTI) ![IMG_7098](https://private-user-images.githubusercontent.com/129564095/351680547-3a2fe618-865b-48f3-a461-2fd27ea1e14e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzI5NDksIm5iZiI6MTcyMTgzMjY0OSwicGF0aCI6Ii8xMjk1NjQwOTUvMzUxNjgwNTQ3LTNhMmZlNjE4LTg2NWItNDhmMy1hNDYxLTJmZDI3ZWExZTE0ZS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjRUMTQ1MDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmU4OGFjYjlmOWJmMzRhMDU5ZDI4NjZkYjA2M2M3OWY4Y2FmYTc5ZTUxZjc2ODNmNWVhNGU5MmJjYzk0OGYxZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.trcN0NMSA9XlpmFojymbtkSjrUXQe_VXeIek6MK0KXo) ![IMG_7095](https://private-user-images.githubusercontent.com/129564095/351680550-7be3d440-3ae4-42be-b21d-bc3e514f1a23.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzI5NDksIm5iZiI6MTcyMTgzMjY0OSwicGF0aCI6Ii8xMjk1NjQwOTUvMzUxNjgwNTUwLTdiZTNkNDQwLTNhZTQtNDJiZS1iMjFkLWJjM2U1MTRmMWEyMy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjRUMTQ1MDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzViN2VlZjdiYzkyNzEzMWZjNGVmY2JkMmJiOGI4ODk2OTA3YTVjZmVjMGQwMTM1YTZiMjRhZDNjMzZjNGEwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.C3nDHwT2uD5bS-WQhTR7W3fUSs-gU8ERxSb_ocjmTxY) ![IMG_7094](https://private-user-images.githubusercontent.com/129564095/351680556-dd67d409-fc59-4805-9d46-ef1b111b4a27.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzI5NDksIm5iZiI6MTcyMTgzMjY0OSwicGF0aCI6Ii8xMjk1NjQwOTUvMzUxNjgwNTU2LWRkNjdkNDA5LWZjNTktNDgwNS05ZDQ2LWVmMWIxMTFiNGEyNy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjRUMTQ1MDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTUxZDUyMWNkOWZjNmJjNzk5OWIyZDAwMjAyMjMxOGM2ZWIxZjE3YTlmZjQ2ZWNlMjAyZmQyMGFmMzUxNTc2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D38auBnUdLNx5SWJGjjsZZuaB7dTgXgaxoRwNJqdvmo)

Again I don't have an issue with the image needing to be converted and those were not the comments I replied to. The issue was the comment where you claimed the cue sheet was wrong and provided one that was actually misformatted claiming it fixed the issue. That just spreads misinformation and redirects blame to the wrong people.

**Comment by tzmwx** [comment]
别人能够看懂，就你看不懂

**Comment by TrekkiesUnite118** [comment]
> 别人能够看懂，就你看不懂
I do understand the issue with image formats Saroo supports. That's not what I replied to. I replied to you claiming the cue sheet the developer included was bad and then providing one that's only difference is it being double spaced. I am simply saying there's nothing wrong with the cue sheet the developer included.

**Comment by tpunix** [comment]
WAV文件实际上是一种容器格式，它里面可以包含除了pcm以外的各种数据流。SAROO没有足够的代码空间去解析这些。所以，带有WAV标记的cue是不被SAROO支持的。如果有人想运行这样的cue，请自行转换格式。
