### ISSUE TITLE
Please share the latest version of firm and boot os.

### ISSUE THREAD

**Issue by hobbylife81** [tpunix/SAROO#18]
Hello, 

Please share the latest version of firm and boot os.

**Comment by xvortex** [comment]
Here we go: 
[saroo_update.zip](https://github.com/tpunix/SAROO/files/13212328/saroo_update.zip)

**Comment by hobbylife81** [comment]
xvortex, Wow!! Thank you~!

**Comment by burnermanx** [comment]
Doesn't work here. Freezes on this screen
![image](https://github.com/tpunix/SAROO/assets/207520/ed3f3e20-4a6e-4f13-ad32-72dbb235fbb5)

**Comment by cyo-the-vile** [comment]
Yep. I had his issue.

TPUNIX has not fixed it.

I had to comment out the serial debug functions in main.c

**Comment by micropixel70** [comment]
It doesn't work for me too, how can I fix it?  Thank you

**Comment by williamdsw** [comment]
@burnermanx @micropixel70
You have to update SAROO using the "update menu" with ssmaster.bin and SSMaster.rbf from zip file first, and then update the ramimage.bin after that. I made a video showing how I did update this.
https://www.youtube.com/watch?v=Mah8CEEyjPg

**Comment by burnermanx** [comment]
It worked! Thanks!

**Comment by tzmwx** [comment]
NEW 20231101 by TPU
[SAROO_20231101.zip](https://github.com/tpunix/SAROO/files/13233520/SAROO_20231101.zip)

NOTE:
STEP 1: UPDATE SSMASTER.BIN
STEP 2: UPDATE RAMIMAGE.BIN

**Comment by micropixel70** [comment]
Hi, I've tried everything but I'm always stuck on the update, what can I fix?  Thank you![IMG_20231102_064329.jpg](https://github.com/tpunix/SAROO/assets/28432797/18a4f49c-2278-4bc9-a4d9-dfe1ea72a5db)

**Comment by xgsh159** [comment]
更新完后，记忆卡管理界面还是只有本体的记忆卡啊。这个功能怎么用啊

**Comment by xvortex** [comment]
I will post new builds of SAROO in my repo: https://github.com/xvortex/SAROO/releases

**Comment by lzibeti** [comment]
> I will post new builds of SAROO in my repo: https://github.com/xvortex/SAROO/releases

Thanks
So now the versions will be centralized in this link?

**Comment by xvortex** [comment]
> Thanks So now the versions will be centralized in this link?

It's my fork of SAROO repo. I'm focused on improving the appearance of the menu, supporting different languages, and fixing minor bugs. In this main repository (https://github.com/tpunix/SAROO) @tpunix decides when to release the official version.

**Comment by lzibeti** [comment]
> > Thanks So now the versions will be centralized in this link?
> 
> It's my fork of SAROO repo. I'm focused on improving the appearance of the menu, supporting different languages, and fixing minor bugs. In this main repository (https://github.com/tpunix/SAROO) @tpunix decides when to release the official version.

I liked the menu font and wallpaper, it reminded me of Krikzz's everdriver.

Thank you for sharing.

**Comment by papaxu** [comment]
> 记忆卡文件会放在SD卡的/SAROO/SS_SAVE.BIN里面。游戏启动后会自动加载相应的存档的。 游戏中退回9球界面，或在选择游戏界面按Z进入9球，可以看到相应的存档。

更新了20231101后sd卡里生成了SS_SAVE.BIN这个文件，可是记忆卡管理界面还是只有本体记录，看不到记忆卡

**Comment by tzmwx** [comment]
> > 记忆卡文件会放在SD卡的/SAROO/SS_SAVE.BIN里面。游戏启动后会自动加载相应的存档的。 游戏中退回9球界面，或在选择游戏界面按Z进入9球，可以看到相应的存档。
> 
> 更新了20231101后sd卡里生成了SS_SAVE.BIN这个文件，可是记忆卡管理界面还是只有本体记录，看不到记忆卡

运行法则是每一个游戏分配一个内置记忆卡！
如何查看？
开机-选择游戏-让光标移动到某一个游戏-按“Z”-进入CD界面-进记忆卡管理界面-可以看到一个大于2倍原机内置记忆卡

**Comment by lzibeti** [comment]
> > > 记忆卡文件会放在SD卡的/SAROO/SS_SAVE.BIN里面。游戏启动后会自动加载相应的存档的。 游戏中退回9球界面，或在选择游戏界面按Z进入9球，可以看到相应的存档。
> > 
> > 
> > 更新了20231101后sd卡里生成了SS_SAVE.BIN这个文件，可是记忆卡管理界面还是只有本体记录，看不到记忆卡
> 
> 运行法则是每一个游戏分配一个内置记忆卡！ 如何查看？ 开机-选择游戏-让光标移动到某一个游戏-按“Z”-进入CD界面-进记忆卡管理界面-可以看到一个大于2倍原机内置记忆卡

I don't know if it's a bug or on purpose but when you do this (load a game by pressing Z) it displays the save of that game that is saved on the SD card (SAROO/SS_SAVE.BIN) in the Saturn options but in practice it saves in console's internal memory.

For example, in Megaman X4 (USA) I can have 2 different saves using this method. Selecting the game with the A button on Saroo saves it to the SD card. Selecting the game with the Z button and then returning to the Saturn menu saves it in the console's internal memory (even if the SD card save appears in the Saturn menu).

I also don't know if this is why, but some games that before update 2231031 worked by selecting them with the A button, now only work by selecting them with the Z button (when selecting with the A button the game freezes on the first loading) and therefore save only in the console's internal memory.

Examples of games that have this problem:
- Marvel Super Heroes (USA)
- Fighters Megamix (USA)
- Fighting Vipers (USA)

**Comment by tzmwx** [comment]
> > > > 记忆卡文件会放在SD卡的/SAROO/SS_SAVE.BIN里面。游戏启动后会自动加载相应的存档的。 游戏中退回9球界面，或在选择游戏界面按Z进入9球，可以看到相应的存档。
> > > 
> > > 
> > > 更新了20231101后sd卡里生成了SS_SAVE.BIN这个文件，可是记忆卡管理界面还是只有本体记录，看不到记忆卡
> > 
> > 
> > 运行法则是每一个游戏分配一个内置记忆卡！ 如何查看？ 开机-选择游戏-让光标移动到某一个游戏-按“Z”-进入CD界面-进记忆卡管理界面-可以看到一个大于2倍原机内置记忆卡
> 
> I don't know if it's a bug or on purpose but when you do this (load a game by pressing Z) it displays the save of that game that is saved on the SD card (SAROO/SS_SAVE.BIN) in the Saturn options but in practice it saves in console's internal memory.
> 
> For example, in Megaman X4 (USA) I can have 2 different saves using this method. Selecting the game with the A button on Saroo saves it to the SD card. Selecting the game with the Z button and then returning to the Saturn menu saves it in the console's internal memory (even if the SD card save appears in the Saturn menu).
> 
> I also don't know if this is why, but some games that before update 2231031 worked by selecting them with the A button, now only work by selecting them with the Z button (when selecting with the A button the game freezes on the first loading) and therefore save only in the console's internal memory.
> 
> Examples of games that have this problem:
> 
> * Marvel Super Heroes (USA)
> * Fighters Megamix (USA)
> * Fighting Vipers (USA)

1.原设计如此，当你从CD界面运行游戏时，将会启用原机内置记忆卡！
2.bug，这是游戏和虚拟记忆卡程序冲突了，因为231031之前的固件不支持虚拟内置记忆卡！等待后续更新。（当你按Z键后为什么能正常运行？因为这时候启用了原机内置记忆卡.）
