### ISSUE TITLE
`ramimage.bin` file purpose

### ISSUE THREAD

**Issue by cystbear** [tpunix/SAROO#191]
According the doc I have:

**SD card file placement**

```
/ramimage.bin ;Saturn firmware program.
```

What this file means?
Is this Saturn bios or what?

**Comment by yzbss** [comment]
Firmware versions on the SS side prior to November 25, 2023 were named ramimage.bin and were located in the root directory of the TF card

All versions of the SS firmware from November 25, 2023 onwards were renamed ssfirm.bin and placed in the SAROO folder

These two files are actually the same, one is used by an earlier version, and the other is used by a later updated version

**Comment by cystbear** [comment]
@yzbss thanks a lot.
Could you please review this question as well https://github.com/tpunix/SAROO/issues/190 ?
