### ISSUE TITLE
No Music in many games if used on Hitachi Hi-Saturn

### ISSUE THREAD

**Issue by choconeco** [tpunix/SAROO#201]
I got a Hitachi Hi-Saturn (MMP-1-1,VA1) and tried to play games using Saroo(v0.6), but the background music does not play in many games. For example, some or all of the music did not play in the following games.The problem has not occurred on the HST-3200, HST-3210, and  HST-3220.I changed ‘sector_delay’ and ‘play_delay’ in saroocfg.txt, but that did not solve the problem.

- Sega Rally Championship Plus [GS-9116   V1.000]
intro and in-race

- Jikkyo Parodius [T-9513G   V1.040]
Konami intro

- Sexy Parodius [T-9514G   V1.040]
Konami intro

- Outrun [GS-9110   V1.005]
all music

If Hi-Saturn is not supported, then this issue is closed.

**Comment by tzmwx** [comment]
Possible problems:
1. The HI-SATURN card slot lacks functional pins, and the relevant pins may have been used for the GPS navigation audio channel. 
2. The HI-SATURN BIOS may be different. 
The above is just speculation. If you are interested, you can open the Saturn shell and upload high-definition pictures of the motherboard, especially the three pin connection lines of the card slot A4\A5\A6 PINS, to see if there is a solution.

**Comment by choconeco** [comment]
I cleaned the connector on the Saroo cartridge with ethanol and that solved the problem. 
Sorry for the trouble. I will close this Issue.
