### ISSUE TITLE
Saroo cartridge not recognized

### ISSUE THREAD

**Issue by Bomberman94** [tpunix/SAROO#207]
My Saturn (Victor - RG-JX1) won’t recognize my Saroo cartridge (old one and brand new with HW V1.3.6). Why? I think the PCB of the Saroo is too thin. If I insert my Pseudo Saturn Kai cartridge it works every time and Saroo never. I heard that this a known problem and isopropyl or insert cartridge and lift it a bit and so on doesn’t change anything. Why don’t anyone simply build a thicker PCB for the Saroo?

Here‘s a picture to see the difference (red is Pseudo and the other a Saroo):

[url=https://postimg.cc/yWbd3ZhK][img]https://i.postimg.cc/yWbd3ZhK/IMG-0893.jpg[/img][/url]

**Comment by tzmwx** [comment]
Neither of your SAROO cards are recognized?
 I recommend:
 1. Check the Saturn cartridge slot. Because SAROO has more golden fingers than PSKAI.
 2.  Make sure again that the TF card format and files are correct.

**Comment by tzmwx** [comment]
The two SAROO cards were working fine before? After you used pskai, they stopped working?

**Comment by Bomberman94** [comment]
Correct - Saroo worked perfectly but after inserting PSKAI never again. So I guess the Pins of PCB of Saroo didn’t have contact anymore. I waited, I cleaned and tried it many times but since then only blinking LED‘s…

**Comment by tzmwx** [comment]
blinking LED？
Check your TF card, only TF card errors (including not inserting TF card, TF card format error, or TF card file error) will flash LED.

**Comment by Bomberman94** [comment]
You‘re right - I prepared a new SD Cart (16GB FAT32) and new files and it worked! In most cases (90%) the menu showed up. I really don’t know why the files on my „old“ cart gets corrupted - will have a look. 

But most important: THIS thread can be closed - thanks **tzmwx** for your great support, I really appreciate it!
