### ISSUE TITLE
Games get paused with the D-pad

### ISSUE THREAD

**Issue by screwbreaker** [tpunix/SAROO#208]
Hi,
I'm having an issue on some games. By playing with the D-pad, like a making full circle, the games get paused, like if the start button is pressed.
All the other buttons, or a single direction button is fine.

The games where I'm having this issue are:
Galaxy Fight (EU)
Night Warriors (EU)
Primal Rage (EU)
Street Fighter Collection (EU)
Street Fighter Zero 3 (JP)
Vampire Savior (JP)
Ultimate Mortal Kombat 3 (EU)

Probably there are more.

**Comment by tzmwx** [comment]
There is a problem with your controller. 
The game program has detected a non-existent button combination: "UP and DOWN", "LEFT and RIGHT".

Please change your controller.

**Comment by screwbreaker** [comment]
I have this issue only on this games.
How a defective gamepad can cause this issue only on some fighting game.
Seems too specific to be an hardware related issue.

**Comment by odiaboeeu** [comment]
It's a problem with controller, I have a controller that has had this problem since 1996, especially in capcom's fighting games

**Comment by tzmwx** [comment]
> I have this issue only on this games. How a defective gamepad can cause this issue only on some fighting game? Seems too specific to be an hardware related issue.

It depends on the design of the game! A plastic sheet with a thickness of 0.5MM can be used to solve the problem.

How to fix it：
First, pull out the DPAD upwards, trim the plastic sheet according to the picture, and install it between the DPAD and the game controller

![IMG_9525](https://github.com/user-attachments/assets/79eed2b9-bdef-4d40-8920-f2bbd7696fee)
![IMG_9523](https://github.com/user-attachments/assets/1f40ff62-d365-4c26-ba6e-ae8d75e476a7)
![IMG_9524](https://github.com/user-attachments/assets/0f07b2dc-2918-40d8-9457-fe46a42fe816)

**Comment by screwbreaker** [comment]
Ok, I'll try with the fix, and with other gamepads.
