### ISSUE TITLE
[0.7] No longer boots to menu

### ISSUE THREAD

**Issue by JonAbrams** [tpunix/SAROO#218]
I was able to successfully update from 0.6 to 0.7. I played a few games. Then while navigating the menu, it froze. After power cycling it now boots to the system menu instead of the SAROO. I’ve tried reseating it. The SD card still looks fine on my PC. I tried copying over the 0.7 files again, no luck. Any ideas?

It was working fine for months on 0.6

**Comment by ragingchaos** [comment]
Try going back to 0.6.

**Comment by tzmwx** [comment]
> I was able to successfully update from 0.6 to 0.7. I played a few games. Then while navigating the menu, it froze. After power cycling it now boots to the system menu instead of the SAROO. I’ve tried reseating it. The SD card still looks fine on my PC. I tried copying over the 0.7 files again, no luck. Any ideas?
> 
> It was working fine for months on 0.6

There are three LEDs on the saroo card. How do they flash? You can make a video and upload it here.

**Comment by JonAbrams** [comment]
The LEDs is can see are solid green. https://youtu.be/z-rBjhlAW4A

**Comment by JonAbrams** [comment]
Overwriting mcuapp.bin and ssfirm.bin from 0.6 didn't fix it.

**Comment by tzmwx** [comment]
The LED on the left side of the Saroo card is not lit up, indicating that Saroo and Saturn have not established communication. 

Possible reasons include: 1. Poor contact between Saroo and the card slot; 2.Saroo is broken; 3. Saturn card slot or hardware is broken. If multiple plugging and unplugging cannot solve the problem, the only solution is to replace the Saturn for testing

**Comment by JonAbrams** [comment]
I actually have a second Saturn (different model, also Japanese), and the problem remains with that one too.

**Comment by JonAbrams** [comment]
Also, I never removed the SAROO after I first plugged it in 6 months ago. I just take out the SD card. It's strange it'd have problems the day after upgrading the firmware. Is there any way for the firmware could cause this? I'd be happy to mail it for debugging.

**Comment by 07saga** [comment]
Clean the SAROO interface and plug and unplug it several times. If it still doesn't work, the FPGA is poorly soldered. You can tell by looking at the outer shell of the card. Many people who bought this card have encountered similar problems.

**Comment by JonAbrams** [comment]
Fiddling with the connector eventually worked. Thanks for the support!
