### ISSUE TITLE
No music in some games after upgrade to version 20231101 by TPU

### ISSUE THREAD

**Issue by paulocarioca** [tpunix/SAROO#22]
@tpunix 

After updating to TPU version 20231101, the songs from KOF 97, KOF 96 and Dragon Ball Shin Butoden do not work. The voices of some Radiant Silvergun characters also don't work. I didn't test other games, however, there was no such sound problem before updating to version 20231101 by TPU.

I have already downgraded to the old version and updated again several times but this bug still persists. Can someone help me? I'm very sad, this version 20231101 only made my Saroo worse.

The 20231031 version was perfect and now I cant turn back to this perfection.

Edit: X-MEN CHILDERN OF ATOM has no music as well.

**Comment by tpunix** [comment]
There have a bug in sound track play. Use this MCU firm and try again!
[ssmaster.zip](https://github.com/tpunix/SAROO/files/13245974/ssmaster.zip)

**Comment by tundertronics** [comment]
I've noticed that when I let the game run the presentations for 3-5 minutes, the music audio works again. At first it sounds a little hoarse, after 5 minutes it's perfect. tested games. pocket fighter, mk trilogy, daytona usa. Saroo versión 11/11/23. Fpga02

**Comment by tundertronics** [comment]
He actualizado fpga a 5  e bajado versión y aun no tengo música de vanda sonora en algunos juegos.
