### ISSUE TITLE
How to Upgrade FPGA Firmware Version

### ISSUE THREAD

**Issue by renyang0911** [tpunix/SAROO#23]
My FPGA firmware version is 02, and I tried upgrading with a tf card, but it didn't work.

**Comment by stakeshadow** [comment]
pay less and you get an inferior product

**Comment by stakeshadow** [comment]
KK's victims

**Comment by tpunix** [comment]
02版的FPGA固件没有升级功能。只能用编程器升级。尽量不要买这种板子。

**Comment by ribenyamazun123** [comment]
It has nothing to do with the board. Upgrading it with a programmer is the same as other boards.

**Comment by cyo-the-vile** [comment]
You do realize the developer is the one that replied to you, right?

**Comment by ribenyamazun123** [comment]
You should ask tpunix why 02 doesn't provide me SD card update

**Comment by yopigo** [comment]
please help i try to update fpga firmware with usb blaster, progress is 100% but found warning message on quartus ii log, 
![sarrrro](https://github.com/tpunix/SAROO/assets/150365171/52beec2d-1e18-4904-9f7e-faa5117874ce)
![log](https://github.com/tpunix/SAROO/assets/150365171/42aed517-958c-4de3-a0b7-5b8e1d7dd56b)

**Comment by yopigo** [comment]
![u8](https://github.com/tpunix/SAROO/assets/150365171/a295a240-64bb-49e3-bb27-c7c7b152d5a4)
is it because of the chip on u8?

**Comment by xvortex** [comment]
> is it because of the chip on u8?
Just ignore this warning. It is OK.

**Comment by yopigo** [comment]
> > is it because of the chip on u8?
> 
> Just ignore this warning. It is OK.

but after update my fpga version stay on 02

**Comment by yopigo** [comment]
i try again but result is same fpga fimware no change,
this is quarus ii log
Info (209060): Started Programmer operation at Wed Nov 15 10:30:59 2023
Info (209016): Configuring device index 1
Info (209017): Device 1 contains JTAG ID code 0x020F10DD
Info (209007): Configuration succeeded -- 1 device(s) configured
Info (209018): Device 1 silicon ID is 0x14
Info (209044): Erasing ASP configuration device(s)
Warning (209074): The attached JTAG Indirect Confgiuration File (.jic) or Programming Object File (.pof), 16Mb, is larger than the Serial Flash device, 8Mb at device 1 -- Only the first 8Mb JTAG Indirect Configuration File or Programming Object File data will be programmed to the device
Info (209023): Programming device(s)
Info (209011): Successfully performed operation(s)
Info (209061): Ended Programmer operation at Wed Nov 15 10:31:19 2023

please help me, whats wrong

**Comment by xvortex** [comment]
Try also check the verify and blank check flags

**Comment by yopigo** [comment]
> Try also check the verify and blank check flags

thank you, but same result, can you give me another tip or anoher file?
![1035fbf3-aec8-40d6-9f18-357c43e436da](https://github.com/tpunix/SAROO/assets/150365171/289e360f-29cf-4024-8479-648a6e573759)

Info (209060): Started Programmer operation at Wed Nov 15 10:30:59 2023
Info (209016): Configuring device index 1
Info (209017): Device 1 contains JTAG ID code 0x020F10DD
Info (209007): Configuration succeeded -- 1 device(s) configured
Info (209018): Device 1 silicon ID is 0x14
Info (209044): Erasing ASP configuration device(s)
Warning (209074): The attached JTAG Indirect Confgiuration File (.jic) or Programming Object File (.pof), 16Mb, is larger than the Serial Flash device, 8Mb at device 1 -- Only the first 8Mb JTAG Indirect Configuration File or Programming Object File data will be programmed to the device
Info (209023): Programming device(s)
Info (209011): Successfully performed operation(s)
Info (209061): Ended Programmer operation at Wed Nov 15 10:31:19 2023

**Comment by xvortex** [comment]
What .jic are you using? Try this one
[ssmaster.jic.zip](https://github.com/tpunix/SAROO/files/13361869/ssmaster.jic.zip)

**Comment by yopigo** [comment]
> What .jic are you using? Try this one [ssmaster.jic.zip](https://github.com/tpunix/SAROO/files/13361869/ssmaster.jic.zip)

tutorial from retro memory on youtube, https://www.youtube.com/watch?v=huaf3aTuMJk, file download from https://drive.google.com/drive/folders/19BPgJ5iUv9Gyi_oBw1esXiZZeMZxIyPR

**Comment by yopigo** [comment]
> What .jic are you using? Try this one [ssmaster.jic.zip](https://github.com/tpunix/SAROO/files/13361869/ssmaster.jic.zip)

Thanks you very much xvortex, my saroo now have fpga:05, log on quartus  is same with ssmaster.jic i use before, but if use file that you give my firmware fpga now 05

**Comment by tpunix** [comment]
The message says that the project usb 16Mb flash chip,  but you have a 8Mb flash chip. 
You can ignore this message.
