### ISSUE TITLE
About saroo, for newbies, how to get debug and program saroo

### ISSUE THREAD

**Issue by luisredo** [tpunix/SAROO#27]
Hello everyone, I am writing to you to obtain a little information, how could I test my saroo, I think it is bricked and I would like to know how to check the FPGA and the stm32, I would also like to know If there is the possibility of obtaining debug to see if saroo starts well, mounts the SD drive and obtains information from the console.

Thank you very much and greetings.
Sorry for my English sponsored by Google translate.

**Comment by tpunix** [comment]
Connect a USB-Serial dongle to SAROO(1Mbps), you will see MCU infomation.
The led on your board is lighting, so they are works fine, I think. What the last version  of your board?

**Comment by luisredo** [comment]
I have version 1.32F, what I don't know is the baudrate or what the RX and TX pins are.
In another post I read things that clarified a little more for me, such as being able to flash the nand without having to use quartus, putting the bin directly into the FPGA flash. Can the stm32 be programmed with a st-link? I saw you commented that you used jlink, I'm not sure if it's the same thing.
![saroo_pines](https://github.com/tpunix/SAROO/assets/21347315/9c764aeb-027d-43e2-a3e6-b2c914aa4b69)

**Comment by tpunix** [comment]
There has error msg:

Mount SDFS: 0000000d
"FR_NO_FILESYSTEM,		/* (13) There is no valid FAT volume */"

Please check your SD Card.

**Comment by tpunix** [comment]
"Can the stm32 be programmed with a st-link? "
Yes. Any xLink can be use.

**Comment by luisredo** [comment]
In other memories I get others but in SDFS it always shows 000000


SSMaster start! 20231005

SDCARD insert!
CMD_08: retv=00000000 resp0=000001aa
    V2.0: Yes
    SDHC: No
    Name: SD01G
    Blen: 512
    Blks: 1888256
    Size: 944128 K
CMD_07: resp=00000700
CMD_16: resp=00000900
ACMD06: resp=00000920
CMD13: resp=00000900
Mount SDFS: 00000000

FPGA config done!
FPGA state:
    config done: 1
      init done: 1
         status: 1

Found Saturn bootrom file.
    Size 00060000
    f_read: retv=0 rv=00060000
stm32> {00}


SSMaster start! 20231005

SDCARD insert!
CMD_08: retv=00000000 resp0=000001aa
    V2.0: Yes
    SDHC: Yes
    Name: SA32G
    Blen: 512
    Blks: 60637184
    Size: 30318592 K
CMD_07: resp=00000700
CMD_16: resp=00000900
ACMD06: resp=00000920
CMD13: resp=00000900
Mount SDFS: 00000000

FPGA config done!
FPGA state:
    config done: 1
      init done: 1
         status: 1

Found Saturn bootrom file.
    Size 00060000
    f_read: retv=0 rv=00060000
stm32> {00}

SSMaster start! 20231005

SDCARD insert!
CMD_08: retv=00000000 resp0=000001aa
    V2.0: Yes
    SDHC: Yes
    Name: SA04G
    Blen: 512
    Blks: 7733248
    Size: 3866624 K
CMD_07: resp=00000700
CMD_16: resp=00000900
ACMD06: resp=00000920
CMD13: resp=00000900
Mount SDFS: 00000000

FPGA config done!
FPGA state:
    config done: 1
      init done: 1
         status: 1

Found Saturn bootrom file.
    Size 00060000
    f_read: retv=0 rv=00060000
stm32> {00}Total discs: 9

**Comment by luisredo** [comment]
hablando con colegas en telegram, les comparti el codigo, y dicen que es raro que detecte el bootrom file en esa direccion de memoria Found Saturn bootrom file. Size 00060000, pero que no monte el SDFS como dices.

> There has error msg:
> 
> Mount SDFS: 0000000d "FR_NO_FILESYSTEM, /* (13) There is no valid FAT volume */"
> 
> Please check your SD Card.

hablando con colegas en telegram, les comparti el codigo, y dicen que es raro que detecte el bootrom file en esa direccion de memoria Found Saturn bootrom file. Size 00060000, pero que no monte el SDFS como dices.

English translate: 

Talking to colleagues on Telegram, I shared the code with them, and they say that it is strange that it detects the bootrom file at that memory address Found Saturn bootrom file. Size 00060000, but it does not mount the SDFS as you say.
