### ISSUE TITLE
Saroo KK DIY Retro game Store vs Saroo Retro game paradise 

### ISSUE THREAD

**Issue by Jot666** [tpunix/SAROO#29]

**Comment by ShowmanBr** [comment]
I had purchase 4 units of the saroo from retro games paradise and all these working perfect. I have nothem to say about other stores!

**Comment by cyo-the-vile** [comment]
Retro games paradise best vendor.

**Comment by stakeshadow** [comment]
KK store price cheap. This is good. The quality may not good as the price. The card looks no clear. Same chip are not in one batch. It may second hand. And there are some grinding on top of chip. I wondering the quality may not good. One more issue is that KK store has write Japan in the ali express product photo. He wants to delude buyer. This is not honest.Retro game paradise saroo price may higher. It looks very clean on board. The chip are all same batch and new. The quality is good.

**Comment by luisredo** [comment]
I received a unit that does not work, it indicates that the stm32 does not have a bootrom, I am already resolving it with the seller.

**Comment by Offi1** [comment]
Had no Problems with seller " Retro game paradise". Updated cartridge around 4 times fine from august when i got it and still running fine.

**Comment by williamdsw** [comment]
I 've bought mine on "Retro Game Paradise Store" and I didn't have problems to update firmware.

**Comment by ShowmanBr** [comment]
> Also you might want to check this thread: https://bbs1-chinaemu-org.translate.goog/read-htm-tid-129500.html?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=pt-BR&_x_tr_pto=wapp&_x_tr_sch=http

Boa noite William!

Vi que você postou aqui um arquivo txt que teoricamente traria mais compatibilidade para alguns jogos. Dentre esses jogo no arquivo vi o kof95, por acaso você conseguiu fazer ele funcionar com essa modificação?

**Comment by williamdsw** [comment]
> > Also you might want to check this thread: https://bbs1-chinaemu-org.translate.goog/read-htm-tid-129500.html?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=pt-BR&_x_tr_pto=wapp&_x_tr_sch=http
> 
> Boa noite William!
> 
> Vi que você postou aqui um arquivo txt que teoricamente traria mais compatibilidade para alguns jogos. Dentre esses jogo no arquivo vi o kof95, por acaso você conseguiu fazer ele funcionar com essa modificação?

Sobre o KOF95, testei aqui e continua não rodando. Acho que só vai rodar quando implementarem o suporte ao cartucho ROm dele. 
Sobre o arquivo txt, creio que você esteja se referindo ao **saroocfg.txt**, que é o arquivo de configuração do SAROO aonde é possível definir o idioma, algumas configurações de leitura para cada jogo (A velocidade de leitura do SAROO com o Saturn é alta, e isso causa alguns glitches e bugs em alguns jogos), além de poder definir um valor para memória do jogo (digo no sentido de hackear, colocar cheat).
Deixo um exemplo de como utilizei esse arquivo para rodar um jogo que tava bugado antes.
https://www.youtube.com/watch?v=gXqanPZoGLw

**Comment by xvortex** [comment]
There is nothing wrong with KK's version. It has no hardware failures.
As I cleared out in the chat with KK, He's mistakenly flashed version 02 in the FPGA, which made it impossible to make a future updates of its firmware (firmware 02 does not release the flash pins).
Project SAROO is still young and such mistakes are typical for a young project. I recommend that everyone (even those with firmware 04) acquire an altera FPGA programmer (ByteBlasterII) and a stm32 programmer (stlink) in case of unforeseen problems with firmware in the future. Fortunately, both of these programmers are inexpensive.
As for FPGA firmware 02, I recommend updating it to 04 since, in addition to flash programming support, it contains some changes regarding fifo and so on.
I'll try to prepare a simple update package which I will upload soon.

**Comment by Jot666** [comment]
I bought the Saroo at the KK retro game store and I didn't see any hardware defects or second-hand components, I found it very similar to the Saroo from the Retrô Paradise game store, I was able to run Metal Slug and Fatal Fury The Final Victory in the Retrô game store Store version I still can't make a saroo comparison because I haven't bought the product from the Retrô game Paradise store yet, the PCB from the KK DIY Retro game Store is in version 1.36 and the PCB from the Retrô game Paradise store is in version 1.35 but both products are Chinese and the only difference is the way they are installed and updated, both are experimental projects, both suppliers are the same thing, the only difference is that one of them chose to do Saroo his way and the other chose to follow the open source , no, I want to create a war here, but I think we should first do tests to highlight its disadvantages and advantages first and then give a verdict, many here are just based on fallacies what counts are the practical results we wouldn't have rockets going into space If we only take into account theories, I'm going to buy the Saroo at the Retrô Paradise game store and I want to make a comparison myself and see which of the two is the most efficient, if anyone here has both Saroo, do rigorous tests between the two everdrives. fair way and bring the results to clear everyone's doubts, if the alternative the Seller's saroo works then I think we are being deceived by unfounded rumors in logistical rivalry and not in real information.

**Comment by LobAnovich** [comment]
> ...acquire an altera FPGA programmer (ByteBlasterII)....

На Алиэкспресс полно ByteBlaster (usb версия) и совсем немного предложений именно,якобы, ByteBlaster II. Внешне они ничем не отличаются от тех же ByteBlaster,коих полно. Но вот цена тех,что якобы ByteBlaster II, в пять раз выше. При том,что на наклейках корпусов последних,нет и намёка,на то,что это именно версия 2. 
Что это, маркетинговый ход предприимчивых продавцов или это реально разные продукты,на разных чипах,просто с одинаковыми внешними корпусами и наклейками ?

**Comment by xvortex** [comment]
Если хотите, чтобы он хоть как-то прошивл, берите самую дешевую версию. Если хотите, чтобы прошивал быстрее, с буферами и как надо, рекомендую версию от waveshare (в белом корпусе) - там все честно - и cpld есть и буфера. По названию выбирать бесполезно. Настоящего оригинального bb2 на али я не встречал.

**Comment by Jot666** [comment]
I just want to thank those responsible and the developer, who brought an excellent project to light, but unfortunately people are taking credit for it and I don't agree.  As soon as possible I will buy from the official Paradise store, but I would like the developer to make his own store available to purchase the product in a 100% official way, as we must respect this master behind wonderful projects like saroo, we must be grateful and avoid investing in products that leave something to be desired and that break the developer's rules, in my case I bought it by accident, I ended up buying it wrong, I thought everything was the same, fortunately the saroo I bought is working very well, apart from updating via USB blaster which is more difficult, I don't want to recommend it to anyone, as I would be disrespecting the developer here and I will never do that, my thanks to him if he reads this message.
