### ISSUE TITLE
New firmware that resolves some game bugs

### ISSUE THREAD

**Issue by jrxoxox** [tpunix/SAROO#30]
https://drive.google.com/file/d/1DRlLsAPftceVn9RhnBGpoH8RBL-xKXdd/view?usp

**Comment by ShowmanBr** [comment]
What kind of bugs its fixed? Could you share more information about the games where you saw the change?

**Comment by cyo-the-vile** [comment]
This isnt how you perform a commit or release.

**Comment by maddrugamers** [comment]
I tested several games that didn't run and didn't find any improvement, it seems so fake!

**Comment by maddrugamers** [comment]
I tested several games that didn't run and didn't find any improvement, it seems so fake!
Eu testei e não vi mudança nenhuma - Parece att fake!

**Comment by ShowmanBr** [comment]
> I tested several games that didn't run and didn't find any improvement, it seems so fake! Eu testei e não vi mudança nenhuma - Parece att fake!

Testou a opção de rodar jogo em cdr (copias) pelo leitor utilizando o saroo pra dar o boot?

**Comment by maddrugamers** [comment]
Testei mais de 30 games que não rodavam, inclusive outrun e testei jogos em CD ... NADA!
