### ISSUE TITLE
my saroo ver.1.32f (paradise store) does not play some games that should play.

### ISSUE THREAD

**Issue by danielsudan** [tpunix/SAROO#31]
my saroo ver.1.32f (paradise store) does not play some games that should play. I'm trying to run the games die hard trilogy, fighters megamix, fighting vipers and others that ran on the same version from the paradise store, 1.32f also acquired from go go games (youtube), in this case it worked, bought it from the same place and same version , for testing, however I did the test on two identical cards, but mine did not reproduce the game, I tested on 5 Sega Saturn, on 3 different cards, and on all firmware, none of them reproduced these games, even in different game regions they did not It doesn't work, this could be a board or update problem @tpunix?

**Comment by danielsudan** [comment]
[ssmaster.zip](https://github.com/tpunix/SAROO/files/13311041/ssmaster.zip)

Usei tbm essa de 03112023

**Comment by lzibeti** [comment]
Choose the game by pressing Z and starting it from the Saturn menu. These games work like this for me after update 231031, which saves the games directly to the SD card.  

Marvel Super Heroes (USA) also works just this way (in addition to disabling the 3MB in the game options).

Interestingly, the Japanese version works normally, selecting with the A button and 3MB in the options.

**Comment by danielsudan** [comment]
[saroocfg.txt](https://github.com/tpunix/SAROO/files/13312970/saroocfg.txt)
[saroo_update_231108.zip](https://github.com/tpunix/SAROO/files/13312971/saroo_update_231108.zip)


Compartilho update vórtex 08/11/2023, e config de Williamdsw.

**Comment by danielsudan** [comment]
[saroocfg.txt](https://github.com/tpunix/SAROO/files/13312970/saroocfg.txt)

[saroo_update_231108.zip](https://github.com/tpunix/SAROO/files/13312971/saroo_update_231108.zip)


Compartilho update vórtex 08/11/2023, e config de Williamdsw.

**Comment by ShowmanBr** [comment]
> [saroocfg.txt](https://github.com/tpunix/SAROO/files/13312970/saroocfg.txt) [saroo_update_231108.zip](https://github.com/tpunix/SAROO/files/13312971/saroo_update_231108.zip)
> 
> Compartilho update vórtex 08/11/2023, e config de Williamdsw.

Esse update trouxe alguma melhoria na compatibilidade dos jogos?

**Comment by danielsudan** [comment]
> > [saroocfg.txt](https://github.com/tpunix/SAROO/files/13312970/saroocfg.txt) [saroo_update_231108.zip](https://github.com/tpunix/SAROO/files/13312971/saroo_update_231108.zip)
> > Compartilho update vórtex 08/11/2023, e config de Williamdsw.
> 
> Esse update trouxe alguma melhoria na compatibilidade dos jogos?

Nos jogos, consegui identificar no TXT, mas foi um outro usuário q o fez, no update do vórtex, teve melhoria no menu

**Comment by tzmwx** [comment]
> my saroo ver.1.32f (paradise store) does not play some games that should play. I'm trying to run the games die hard trilogy, fighters megamix, fighting vipers and others that ran on the same version from the paradise store, 1.32f also acquired from go go games (youtube), in this case it worked, bought it from the same place and same version , for testing, however I did the test on two identical cards, but mine did not reproduce the game, I tested on 5 Sega Saturn, on 3 different cards, and on all firmware, none of them reproduced these games, even in different game regions they did not It doesn't work, this could be a board or update problem @tpunix?

新版固件启用了“虚拟内置记忆卡”，存在BUG，和一些游戏冲突：
如何正常运行这些游戏？
方法1:降级到20231005或20230419（V 0.1 ）没有虚拟内置记忆卡版本
方法2:在游戏名称上按Z键，进入CD界面再按START键运行游戏
方法3:等待后续更新

**Comment by danielsudan** [comment]
> > my saroo ver.1.32f (paradise store) does not play some games that should play. I'm trying to run the games die hard trilogy, fighters megamix, fighting vipers and others that ran on the same version from the paradise store, 1.32f also acquired from go go games (youtube), in this case it worked, bought it from the same place and same version , for testing, however I did the test on two identical cards, but mine did not reproduce the game, I tested on 5 Sega Saturn, on 3 different cards, and on all firmware, none of them reproduced these games, even in different game regions they did not It doesn't work, this could be a board or update problem @tpunix?
> 
> 新版固件启用了“虚拟内置记忆卡”，存在BUG，和一些游戏冲突： 如何正常运行这些游戏？ 方法1:降级到20231005或20230419（V 0.1 ）没有虚拟内置记忆卡版本 方法2:在游戏名称上按Z键，进入CD界面再按START键运行游戏 方法3:等待后续更新

Downgrade para 20231005 ou 20230419 (V 0.1) sem versão do cartão de memória virtual integrado Método 2: No nome do jogo
 Pressione a tecla Z para entrar na interface do CD e pressione a tecla START para iniciar o jogo. Método 3: Aguarde as atualizações subsequentes.
