### ISSUE TITLE
About savegames

### ISSUE THREAD

**Issue by Agentmanbh** [tpunix/SAROO#33]
Can you explain how works save feature?
I'm playing POWERSLAVE (USA) and sometimes savefile doesn't update after powercicle or reset console and some game progress is lost.

**Comment by tzmwx** [comment]
针对20231111固件：

20231111固件为每一个游戏模拟了一张内置记忆卡，容量1020格，是原机内置记忆卡的2倍多；

注意：一个游戏一张虚拟记忆卡

如何使用虚拟的内置记忆卡：
当你在游戏目录时，选择某个游戏名称后按压手柄“A”键进入游戏，SAROO将根据你的游戏官方编号生成一个专用的虚拟内置记忆卡，此游戏的所有存档数据存在于这个专用的空间内。


如何查看和管理某个游戏在虚拟记忆卡中内容：
方法1：在游戏中多次同时按压手柄START+A+B+C键，直至退回到世嘉土星将进入CD播放器界面，你可以在官方的记忆卡管理界面，内置记忆卡栏里看到和管理这张虚拟的记忆卡及内容。
方法2：在游戏目录选中一个游戏，按压手柄“Z”键，世嘉土星将进入CD播放器界面，SAROO将根据你的游戏官方编号将对应的虚拟内置记忆卡文件镜像到记忆卡管理系统，你可以在官方的记忆卡管理界面，内置记忆卡栏里看到和管理这张虚拟的记忆卡及内容。

如何使用原机内置记忆卡：
方法1：在游戏中多次同时按压手柄START+A+B+C键，世嘉土星将进入CD播放器界面，再按压START进入游戏；
方法2：当你在游戏菜单使用按压手柄“Z”键，世嘉土星将进入CD播放器界面，再按压START进入游戏；
方法1和方法2不适用于需要1M/4M扩展卡的游戏，在按压START进入游戏时，SAROO不再使用1M/4M扩展卡和虚拟内置记忆卡。

**Comment by Agentmanbh** [comment]
Thank you for reply.
Ok, I understood your explanation, but POWERSLAVE (USA) doesn't works well.
For some reason, that game don't save properly. Sometimes game saves normal after some game progress, but sometimes don't saves progress after one stage even.
