### ISSUE TITLE
请教下如何为FPGA下载程序？我使用USB BLASTER遇到一些问题

### ISSUE THREAD

**Issue by xiuhui-wang** [tpunix/SAROO#38]
您好，很抱歉打扰您，我复刻了这个项目，但是在FPGA烧录程序这里遇到了问题。

1.我编译了 FPGA的固件，他提示成功，但是在我点PROGRAMMER按钮后，对话框显示 CANNOT OPEN FILE C:XXXX/FPGA/SSMASTER.CDF。。。。。
![1701697839283](https://github.com/tpunix/SAROO/assets/112448037/13913ed6-a5eb-4dd4-972f-112dbab32266)

2. 但我最大的问题，我已经在这里研究了2天了，依然无法下载固件到FPGA中，我短接了 R6与R20，R7与R21是断开的，请问这是正确的么？

3.固件程序是要下载到U8中么？因为我现在不确定是我的FPGA芯片还是FLASH芯片的问题。。。。 

很抱歉问这么简单的问题。。。

另外我检查了，3组电压，3.3V 2.5V 1.2V都存在。
也测试了50M的晶振工作正常。。。。

**Comment by xiuhui-wang** [comment]
一直显示无法连接，请教一下有什么需要注意的地方的么？

![a2](https://github.com/tpunix/SAROO/assets/112448037/65e9cc26-c49e-4ae7-a65d-1d98dc5ad514)
![A3](https://github.com/tpunix/SAROO/assets/112448037/f0f56465-1ba1-4615-8304-710eb5b5cb62)

**Comment by xiuhui-wang** [comment]
我拆除了2个芯片，又外接了 3.3V 与1.2V的电源。。。 目前问题依旧，是不是我的下载器有问题呢？我用他下载 CPLD 是没问题的 可以下载。。。。 目前卡死在这里 几天了
![c51e059a497681bd547fd8a2320602f](https://github.com/tpunix/SAROO/assets/112448037/60d608ff-595d-4c4b-88f6-7a776560d772)
![57ea0a79e1970c3f9b11fa2e0bd4a6d](https://github.com/tpunix/SAROO/assets/112448037/b94e4357-d72f-4b1c-9520-5b1abef562a2)

**Comment by tpunix** [comment]
FPGA固件是写到U8里面的，你把它拆了吗？
另外，先写MCU固件再看看。

**Comment by xiuhui-wang** [comment]
mcu的固件我已经写进去了，会有一个 LED 一直闪啊闪的。 U8 拆不拆我都写不进去。。。。 有没有其他手段？ 比如我用 编程器直接写U8。。。。 我的 USB BLASTER 就是 淘宝最便宜的那种, 目前我又订购了一个编程器看看。。。。 目前不确定是 PCB板子，芯片或者编程器的问题。。。
U8 我使用 编程器检测过，虽然是翻新的但是可以正常工作。。。
![44a0c050d21f813d4711f13edda59e5](https://github.com/tpunix/SAROO/assets/112448037/5aa7b35e-386b-47ca-a9a3-5c1b044ec104)

**Comment by tzmwx** [comment]
https://github.com/tpunix/SAROO/issues/2#issuecomment-1642263770

这里有用编程器直接烧录U8的固件

**Comment by tpunix** [comment]
如果电压正常，晶振正常，还连不上，只能怀疑是芯片或焊接问题。

**Comment by xiuhui-wang** [comment]
> 如果电压正常，晶振正常，还连不上，只能怀疑是芯片或焊接问题。

我已经确定我其中的一个 USB Blaster 不能使用，里面是WCH芯片的，上电只有一个LED红灯。虽然他可以下载CPLD，因为我又买了一套开发板。

**Comment by xiuhui-wang** [comment]
目前我在研究芯片与焊接问题。。。 解决后我会更新。。。 R6 与 R20 接0R 是正确的吧？

**Comment by tzmwx** [comment]
> 目前我在研究芯片与焊接问题。。。 解决后我会更新。。。 R6 与 R20 接0R 是正确的吧？

看我发你的连接，你直接编程器写好U8，看能不能点亮D2

**Comment by xiuhui-wang** [comment]
> > 目前我在研究芯片与焊接问题。。。 解决后我会更新。。。 R6 与 R20 接0R 是正确的吧？
> 
> 看我发你的连接，你直接编程器写好U8，看能不能点亮D2

我烧录了U8，使用编程器，但是遗憾的是D2 不能点亮。。。。
![1701839096771](https://github.com/tpunix/SAROO/assets/112448037/9b0a373f-13f4-4979-b70f-e163b67955c8)

**Comment by tzmwx** [comment]
确认烧录了ssmaster.rbf.bin点不亮D2说明可能flasb与fpga有电路不通，或者是FPGA芯片的问题。内存有没有贴回去？

要不就用串口接saroo右上角看一下数据，速度10000，看看报错数据

**Comment by xiuhui-wang** [comment]
> 确认烧录了ssmaster.rbf.bin点不亮D2说明可能flash与fpga有电路不通，或者是FPGA芯片的问题。内存有没有贴回去？
> 
> 要不就用串口接saroo右上角看一下数据，速度10000，看看报错数据

目前LED的状态 是 LED1 闪几下 然后 红色的 长亮
其他LED 不亮


SSMaster start! 20231203

No SDCARD insert!
disk_read: pdrv=0 sector=00000000 count=1
    retv=ffffffff
disk_read: pdrv=0 sector=00000000 count=1
    retv=ffffffff
disk_read: pdrv=0 sector=00000000 count=1
    retv=ffffffff
disk_read: pdrv=0 sector=00000000 count=1
    retv=ffffffff
Mount SDFS: 00000001

FPGA config done!
FPGA state:
    config done: 1
      init done: 1
         status: 1

disk_read: pdrv=0 sector=00000000 count=1
    retv=ffffffff
disk_read: pdrv=0 sector=00000000 count=1
    retv=ffffffff
disk_read: pdrv=0 sector=00000000 count=1
    retv=ffffffff
disk_read: pdrv=0 sector=00000000 count=1
    retv=ffffffff
disk_read: pdrv=0 sector=00000000 count=1
    retv=ffffffff
disk_read: pdrv=0 sector=00000000 count=1
    retv=ffffffff
disk_read: pdrv=0 sector=00000000 count=1
    retv=ffffffff
disk_read: pdrv=0 sector=00000000 count=1
    retv=ffffffff
NO bootrom file found!
stm32>

**Comment by tzmwx** [comment]
红色是D2？
led1开机就闪烁是没有检测到tf卡
看你的串口信息应该是只要将（saroo主页右侧下载的）0.1版的ramimage.bin拷贝到fat32格式的tf卡根目录插上土星开机即可
第一次使用多插拔几次，确保接触良好

此卡有+5V电源输入时，你要确保D1（闪烁或常亮）和D2常亮基本就好了
D3必须进入saroo菜单后才会亮

**Comment by xiuhui-wang** [comment]
> 红色是D2？ led1开机就闪烁是没有检测到tf卡 看你的串口信息应该是只要将（saroo主页右侧下载的）0.1版的ramimage.bin拷贝到fat32格式的tf卡根目录插上土星开机即可 第一次使用多插拔几次，确保接触良好
> 
> 此卡有+5V电源输入时，你要确保D1（闪烁或常亮）和D2常亮基本就好了 D3必须进入saroo菜单后才会亮

SSMaster start! 20231203

SDCARD insert!
CMD_08: retv=00000000 resp0=000001aa
    V2.0: Yes
    SDHC: Yes
    Name: SS08G
    Blen: 512
    Blks: 15523840
    Size: 7761920 K
CMD_07: resp=00000700
CMD_16: resp=00000900
ACMD06: resp=00000920
CMD13: resp=00000900
Mount SDFS: 00000000

FPGA config done!
FPGA state:
    config done: 1
      init done: 1
         status: 1

这是我目前的状态，D1已经常亮，其他的都不亮。。。 难道是我D2损坏了？

**Comment by tzmwx** [comment]
那估计你的fpga芯片问题，或者焊接不良

提醒一下，这卡的fpga和内存芯片绝对不要从tb去购买

**Comment by xiuhui-wang** [comment]
> 那估计你的fpga芯片问题，或者焊接不良
> 
> 提醒一下，这卡的fpga和内存芯片绝对不要从tb去购买

已经在淘宝购买了。。。。。。 内存芯片 感觉不像是翻新的 FPGA 就是那家13块包邮的 我已经买了5个了。。。。。FLASH SST 那个 是重新打字的。。。。

**Comment by xiuhui-wang** [comment]
目前还是不行，插在机器里 跟没插一样，还需要继续寻找问题的答案

**Comment by tzmwx** [comment]
点灯顺序D1、D2亮后才有D3亮
建议重新做一下BGA看看，不行就换芯片，换大品牌供应商的芯片

**Comment by xiuhui-wang** [comment]
> > 目前我在研究芯片与焊接问题。。。 解决后我会更新。。。 R6 与 R20 接0R 是正确的吧？
> 
> 看我发你的连接，你直接编程器写好U8，看能不能点亮D2

OK 我现在写一下

> 点灯顺序D1、D2亮后才有D3亮 建议重新做一下BGA看看，不行就换芯片，换大品牌供应商的芯片

是的目前我正在尝试换芯片，应该是装不装内存芯片都可以 连上 FPGA吧？ 因为我现在不确定他俩哪个又问题 我需要先确认出一个

**Comment by xiuhui-wang** [comment]
SSMaster start! 20231203

SDCARD insert!
CMD_08: retv=00000000 resp0=000001aa
    V2.0: Yes
    SDHC: Yes
    Name: SS08G
    Blen: 512
    Blks: 15523840
    Size: 7761920 K
CMD_07: resp=00000700
CMD_16: resp=00000900
ACMD06: resp=00000920
CMD13: resp=00000900
Mount SDFS: 00000000

FPGA config done!
FPGA state:
    config done: 1
      init done: 0
         status: 1

Found Saturn bootrom file.
    Size 00060000
    f_read: retv=0 rv=00060000
stm32> Total discs: 1

这是我目前的状态，我安装了一个游戏，界面是自动出现的么？ 还是需要进行什么特殊的操作？

**Comment by tzmwx** [comment]
U7和U13是不需要的，可以不用
D3需要saroo和土星建立通讯后才会亮，D3亮后土星也会进到saroo菜单了

所以现在你要做的是检查为什么没有建立通讯，可能：1卡槽接触不良；2四片电平芯片164245焊接不良或损坏；3FPGA芯片焊接不良或损坏

**Comment by tzmwx** [comment]
内存tb购买100%翻新，但不会坏的那么巧导致点不亮屏幕，或者换一片试试看

注意mcu和tf卡里的ramimage.bin用一个版本

用0.1固件测试是只有一个ramimage.bin就能启动，不需要saroo文件夹就可以进菜单

**Comment by tzmwx** [comment]
你用统一0.1，先把土星点亮
FPGA先用编程器刷入上面链接里那个04直刷flash芯片版本，
MCU就用0.1固件包里的ssmaster.bin
tf卡里也用0.1固件包里的ramimage.bin

**Comment by xiuhui-wang** [comment]
源码在我这面是这样，都是说禁用中断那个返回的类型错误。 我修正了这些 才能编译的下去。。


 
![1701865681894](https://github.com/tpunix/SAROO/assets/112448037/c2decfb2-d580-412e-9846-3edef4034b86)

**Comment by tzmwx** [comment]
你不用去考虑编译源代码，听我的，你用统一0.1固件，先把土星点亮再说

**Comment by xiuhui-wang** [comment]
> 你不用去考虑编译源代码，听我的，你用统一0.1固件，先把土星点亮再说

你的思路是正确的，应该先想办法确认硬件是没有问题。
我使用0.1 的固件中的三个文件
ramimage.bin --- > TF card
ssmaster.bin --- > STM32
SSMaster.rbf --- > U8 SST25VF080 FLASH
现在情况可能不太乐观，还不如之前了，只有一个 LED D1 是亮的。



SSMaster start! Apr 19 2023 22:36:20

SDCARD insert!
CMD_08: retv=00000000 resp0=000001aa
    V2.0: Yes
    SDHC: Yes
    Name: SS08G
    Blen: 512
    Blks: 15523840
    Size: 7761920 K
CMD_07: resp=00000700
CMD_16: resp=00000900
ACMD06: resp=00000920
CMD13: resp=00000900
Mount SDFS: 00000000

FPGA config timeout!
FPGA state:
    config done: 0
      init done: 0
         status: 1

Found Saturn bootrom file.
    Size 00060000

会显示 FPGA 没有设置，然后后面会疯狂的发送数据出来。。。。

**Comment by tzmwx** [comment]
u8用我发你链接里的ssmaster.rbf.bin，另外两个对的

**Comment by xiuhui-wang** [comment]
> u8用我发你链接里的ssmaster.rbf.bin，另外两个对的
OK 我更改了，现在亮了 两个LED了，开机到9球，串口信息如下：

SSMaster start! Apr 19 2023 22:36:20

SDCARD insert!
CMD_08: retv=00000000 resp0=000001aa
    V2.0: Yes
    SDHC: Yes
    Name: SS08G
    Blen: 512
    Blks: 15523840
    Size: 7761920 K
CMD_07: resp=00000700
CMD_16: resp=00000900
ACMD06: resp=00000920
CMD13: resp=00000900
Mount SDFS: 00000000

FPGA config done!
FPGA state:
    config done: 1
      init done: 0
         status: 1

Found Saturn bootrom file.
    Size 00060000
    f_read: retv=0 rv=00060000
stm32> {00}{00}{00}{00}{00}{00}{00}{00}{00}{00}{00}{00}{00}{00}{00}{00}{00}{00}{00}{00}{00}{00}{00}{00}{00}{00}{00}{000}{00}{00}{00}{000}{00}{00}{00}{000}{00}{00}{00}{000}{00}{00}{00}{000}{00}{00}{00}{000}{00}{00}{00}{000}{00}{
stm32> 00}{00}{000}{00}{
stm32> 
stm32> 
stm32> stm32> 00}{0}{
stm32> 
stm32> 
stm32> stm32> 
stm32> 
stm32> 
stm32> stm32> 
stm32> tm32> 
stm32> 
stm32> 
stm32> stm32> 
stm32> 
stm32> 
stm32> stm 
stm32> 
stm32> 
stm32> stm32> 

好像是FPGA 初始化失败

**Comment by xiuhui-wang** [comment]
能给我一个 最新的 TF卡里的固件么？ 我想试试都是新版本 会怎么样

**Comment by xiuhui-wang** [comment]
SSMaster start! Apr 19 2023 22:36:20

SDCARD insert!
CMD_08: retv=00000000 resp0=000001aa
    V2.0: Yes
    SDHC: Yes
    Name: SS08G
    Blen: 512
    Blks: 15523840
    Size: 7761920 K
CMD_07: resp=00000700
CMD_16: resp=00000900
ACMD06: resp=00000920
CMD13: resp=00000900
Mount SDFS: 00000000

FPGA config done!
FPGA state:
    config done: 1
      init done: 1
         status: 1

Found Saturn bootrom file.
    Size 00060000
    f_read: retv=0 rv=00060000
stm32> {00}SS CDC: unknow cmd!  CR1=

**Comment by xiuhui-wang** [comment]
非常感谢今天的帮助，太不容易了，我得到了界面。 思路是对的仅供参考。谢谢 [tzmwx](https://github.com/tzmwx)


![4dfbe58952b79760156f7e6ce094cf0](https://github.com/tpunix/SAROO/assets/112448037/46017f29-db4b-42e7-a7d3-e8fd39fcd922)

**Comment by tzmwx** [comment]
最终什么原因总结一下发个流程，便于人家借鉴！

**Comment by xiuhui-wang** [comment]
get_auth_status
get_auth_status
get_auth_status
get_auth_status
get_auth_status
get_auth_status
get_auth_status

我高兴的有点太早了。。。。 目前启动不了任何游戏。。。 串口不停的这个。。。 然后会显示游戏启动中。。。。 就这样了

**Comment by tpunix** [comment]
> get_auth_status get_auth_status get_auth_status get_auth_status get_auth_status get_auth_status get_auth_status
> 
> 我高兴的有点太早了。。。。 目前启动不了任何游戏。。。 串口不停的这个。。。 然后会显示游戏启动中。。。。 就这样了

这是解析cue文件失败了的现象，mcu端游戏镜像加载失败了。

**Comment by xiuhui-wang** [comment]
> > get_auth_status get_auth_status get_auth_status get_auth_status get_auth_status get_auth_status get_auth_status
> > 我高兴的有点太早了。。。。 目前启动不了任何游戏。。。 串口不停的这个。。。 然后会显示游戏启动中。。。。 就这样了
> 
> 这是解析cue文件失败了的现象，mcu端游戏镜像加载失败了。

是的现在我已经基本能用了，我将继续探索，那个 KOF2 95 您可以运行么？我进去以后 说ROM 卡带错误，让重新插入
