### ISSUE TITLE
What's the largest TF card supported?

### ISSUE THREAD

**Issue by xiuhui-wang** [tpunix/SAROO#39]
Excuse me, i have a 256G TF card but don't support it.

**Comment by TheUndertakerPoland** [comment]
Mine was working fine, 256gb and 512gb

**Comment by TheUndertakerPoland** [comment]
I have tested sandisk and Samsung were fine

**Comment by xiuhui-wang** [comment]
I just bought it from JD made.......
![1104f0dbd77319ae54ed046f2684c36](https://github.com/tpunix/SAROO/assets/112448037/cb749d2d-d0c5-44b9-8126-d7246d5f0845)

**Comment by xiuhui-wang** [comment]
![76cf90e377b6cd19b62daa726f85747](https://github.com/tpunix/SAROO/assets/112448037/98ed9d78-55ad-47e7-a872-fa5d466a8b69)

**Comment by xiuhui-wang** [comment]
SSMaster start! 20231206

SDCARD insert!
CMD_08: retv=00000000 resp0=000001aa
    V2.0: Yes
    SDHC: Yes
    Name: USD00
    Blen: 512
    Blks: 489062400
    Size: 244531200 K
CMD_07: resp=00000700
CMD_16: resp=00000900
ACMD06: resp=00000920
CMD13: resp=00000900
Mount SDFS: 0000000d

FPGA config done!
FPGA state:
    config done: 1
      init done: 1
         status: 1

NO bootrom file found!

**Comment by xiuhui-wang** [comment]
It says no file but it is there.

**Comment by tpunix** [comment]
SAROO need FAT32 filesystem. Next release will add exfat support.

**Comment by xiuhui-wang** [comment]
> SAROO need FAT32 filesystem. Next release will add exfat support.
OK,Thanks. Format to FAT32 and works well.
