### ISSUE TITLE
Saroo's dashboard doesn't enter!

### ISSUE THREAD

**Issue by binhoxp03** [tpunix/SAROO#41]
Good afternoon, my Saroo version 1.32f, only lights up two green lights, where one is fixed and the other is flashing and is on the Sega Saturno dashboard. I already changed the SD card and nothing, can anyone help me solve it? Note: I cleaned the console with isopropyl alcohol and nothing, my console is unlocked by a chip that connects to the CD drive). I await a response and thank you.

**Comment by LobAnovich** [comment]
If you have not used a flash cartridge before, then you need to install the updated firmware using the seller’s link dated November 25th.  The location structure and file names have already been changed

**Comment by morpheu** [comment]
Hi @binhoxp03 , have you already solved your problem? I got exactly same issue - a fixed green light and another green blink ing - saroo cartridge not recognized and fallback to cd player screen
