### ISSUE TITLE
Saroo and Retro-Bit 2.4g controller issue.

### ISSUE THREAD

**Issue by Skex420** [tpunix/SAROO#45]
Hello team,
First of all, I wanted to say thank you for working on this amazing project. So far, I haven't encountered any major issues, so I'm excited to see how this evolves and gets even better.

I wanted to bring up an issue with the 2.4Ghz controllers from Retro-Bit. For some reason, once you press a d-pad to scroll down the list of games, it gets stuck. I have to basically unplug these, plug the OEM controllers to select the game and then plug them back if I want to use them.
I'm not sure if this is Saroo related but it's something that might be cool to fix eventually.

Thanks in advance!

**Comment by tpunix** [comment]
I test it with retroblue+ds4, scroll not work in menu when change the map. I'll debug it later.

**Comment by williamdsw** [comment]
I have tested with a 8bitdo M30 controller + Blueretro bluetooth adapter and does work without problems.

**Comment by Skex420** [comment]
Hello, @tpunix , I just wanted to let you know that the issue is still present in the 0.3 firm. Once you enter the game you can actually use the controllers, but when you're navigating through the menu is when it happens.

**Comment by abgamess** [comment]
> Olá,@tpunix, só queria que você soubesse que o problema ainda está presente na empresa 0,3. Depois de entrar no jogo, você pode realmente usar os controladores, mas é quando você navega pelo menu que isso acontece.

I have the same problem, I use the 2.4ghz retro-bit controller on my Sega Saturn

**Comment by Skex420** [comment]
Hey @tpunix the same issue is happening even in v0.6. If there is anything I can do to help you debug this, please let me know!

**Comment by jakej1020** [comment]
@tpunix I also have this issue.

**Comment by Skex420** [comment]
> I have tested with a 8bitdo M30 controller + Blueretro bluetooth adapter and does work without problems.

I'm talking specifically about 2.4g controllers, not bluetooth. I'm not aware that bluetooth has issues, but with the Retro-Bit 2.4g controllers it gets stuck on whatever direction you try to navigate throughout the menu.

**Comment by jaraiza** [comment]
@tpunix  Hi, I've just bought saroo, updated firmware files and I've the same issue with "Retro-Bit SEGA Saturn® 2.4GHz Wireless Pro Controller for Sega Saturn" sold by Amazon. :(

**Comment by tpunix** [comment]
I'm sorry but i dont have this controller ......

**Comment by Skex420** [comment]
@tpunix Is there a chance that you can buy one? Since I'm not sure what capabilities you have at home, I can send you money so you can buy it (if it's possible) so you can test it and debug it yourself. Please let me know if that's a possibility, I'm happy to support you if needed.

**Comment by Skex420** [comment]
@tpunix this worked like a charm. Amazing work and thanks to #177 for bringing this easy fix to our attention!
