### ISSUE TITLE
Error on Zero Divide 2 - The Final Conflict [T-31601G  V1.003]

### ISSUE THREAD

**Issue by Shoometsu** [tpunix/SAROO#46]
Tested with firm 0.3.

Game stop at black screen after the Zoom intro, we can hear SFX but the game doesn't go forward. Tried with sector_delay up to 24000 without success.

**Comment by tpunix** [comment]
It work on v0.2?

**Comment by Shoometsu** [comment]
Nope, didn't work too. Just ensuring I'm using the latest version available before opening this issue.

**Comment by williamdsw** [comment]
Can you try this?
<pre># ZERO DIVIDE THE FINAL CONFLICT (J)
[T-31601G  V1.003]
play_delay=2000</pre>

https://youtu.be/3CKU4rAsNac

**Comment by Shoometsu** [comment]
> Can you try this?
> 
> # ZERO DIVIDE THE FINAL CONFLICT (J)
> [T-31601G  V1.003]
> play_delay=2000
> https://youtu.be/3CKU4rAsNac

Wow, worked perfectly. Thanks!
