### ISSUE TITLE
KOF95 on v0.3 firm

### ISSUE THREAD

**Issue by Jungkyu-Lee** [tpunix/SAROO#49]
Thank you for letting me run my favorite game, KOF95, in this version up.

When I actually ran KOF95, it ran very well.

However, after 3 or 4 stages, the game resets and jumps to the Saturn CD player screen.

I was wondering if this is just me and if there is a way to fix this.

**Comment by SONIC3D** [comment]
There are similar cases for this game reported in local online chating groups with the recent update.

Please try to provide the following information for better reproducing and tracing this potential issue:
1. You console mainboard type.
2. Boot ROM version(if you can see it on the bottom right of the splash screen after the Sega Saturn power-up animation).
3. Console VDP type(Display type: PAL/NTSC).
4. Is the power supply board modded or replaced with any 3rd party model?
5. Is MPEG(VCD) card inserted.
6. Is the joypad Sega original model or 3rd party model(include wireless receiver).
7. Run KOF95 without start the game play, make it enter the demo play loop. Check if it will jump back to the saturn CD Player after several loops.

**Comment by Agentmanbh** [comment]
About 7th question, first time I've tested KOF '95, occurs jump back menu during demo play after some few loopings....

**Comment by deividjaime** [comment]
I'm having the same problem with my Saturn on Kof 95. 
Including with games that work on other Saturn's and don't work well on mine (Resident Evil, Mr. Bones, Deep Fear, etc.).

1 - HST-3220
2 - ver 1.01
3 - NTSC
4 - NO
5 - NO
6 - Original Joy Pad
7 - Yes, and during gameplay too (20 minutes in a demo play loop)

**Comment by odiaboeeu** [comment]
I tested it with some sector delay settings from 2k up to 12k and with 8k it was the one that managed to go the furthest missing one fight for the final fight with Rugal, but you can see that the problem is random.

I believe it has something to do with the music or sfx sounds.

With sector delay above 8k significantly increased loading time and also twice occurred to freeze the game on a black screen with sfx sound in a loop.

**Comment by williamdsw** [comment]
What version of KOF 95 are you testing?
Note that based on [game_patch.c](https://github.com/tpunix/SAROO/blob/8928b7da7311edb65b7b2d0e9fd1989cc25c4202/Firm_Saturn/game_patch.c#L221C19-L221C20) file, it was only patched for the 2MB version of the japanese version (T-3101G).
**King of Fighters '95, The (Japan) (2M)**

**Comment by odiaboeeu** [comment]
The version I used is 3M Hmm I'll try it with 2M

Maybe it would be better to make the same patch for all versions or at least put in the Readme which versions were used in the patch 

Marvel super heroes US version could put the same patch they have in the Japanese version

**Comment by odiaboeeu** [comment]
Version 2m of the redump gave same problem

**Comment by odiaboeeu** [comment]
I've done more tests and it keeps crashing randomly, sometimes even characters from the team that stays in the stage have graphics problems in team China and team Korea

![IMG_20240121_173347426_HDR](https://github.com/tpunix/SAROO/assets/55262527/b9b39714-beb5-4755-93ee-d5a0314bc7c4)

**Comment by odiaboeeu** [comment]
@tpunix Could you add the European version of kof95 to work on kof95.bin?

**Comment by tpunix** [comment]
I'll add it later. This game need debug more and more...

**Comment by Jungkyu-Lee** [comment]
1. I tried "King of Fighters '95, The (Japan) (2M)" rom => also jump back to CD player
2. I tried "single play mode" not "team play" => it works nomally

**Comment by Jungkyu-Lee** [comment]
> Thanks for reply.
> 
> I'll answer as much as I know
> 
> 1. HST-3220
> 2. ver 1.01
> 3. NTSC
> 4. NO
> 5. NO
> 6. Original Joy Pad
> 7. Does not jump back during demo playback.

1. I tried "King of Fighters '95, The (Japan) (2M)" rom => also jump back to CD player
2. I tried "single play mode" not "team play" => it works nomally
