### ISSUE TITLE
Erro on Cyberbots (JP) [T-1217G V1.002]

### ISSUE THREAD

**Issue by odiaboeeu** [tpunix/SAROO#50]
Hi this one is also having same problem since the old version of the firmware. Sometimes it freezes after the capcom logo and sometimes it starts, using the z has a better chance of success starting and passing through the capcom logo. 

Another problem is with the robots' graphics that get graphical errors and when you enter the options it often crashes the game. 

It was tested with sector delay from 1000 to 24000 also with play delay up to 3000, improved freezing of the capcom logo, but the other two reported problems persist. 

Note: bios of my saturn is ntsc and version 1.0a

**Comment by odiaboeeu** [comment]
Disabling 3mb ram mode graphics error on robots stop occurring

**Comment by tpunix** [comment]
This game will be fix at next release.

**Comment by odiaboeeu** [comment]
Fix on firmware 0.4
