### ISSUE TITLE
Erro on Sonic Jam (US) and (JP) [MK-81079 V1.004]

### ISSUE THREAD

**Issue by odiaboeeu** [tpunix/SAROO#51]
In all Sonic games, music stops working randomly during gameplay. 
This is a problem that comes from the previous firmware.

Tests were carried out with delay sector 1000 to 12000 without any effect

**Comment by keeper7keys** [comment]
The japanese version have the same issues.

**Comment by odiaboeeu** [comment]
Fix on firmware 0.4
