### ISSUE TITLE
Erro FALCOM CLASSICS II  [T-31505G V1.004]

### ISSUE THREAD

**Issue by box1694** [tpunix/SAROO#52]
On the title screen, I press start, but there is no response and I cannot enter the game.

thank you for your hard work

**Comment by tpunix** [comment]
This game can run randomly with large play_delay(30000). It's hard to trace ......

**Comment by tpunix** [comment]
Please try "play_delay = 50000"

**Comment by box1694** [comment]
like this?  it`s same 
# FALCOM CLASSICS II 
[T-31505G V1.004]
play_delay = 50000

**Comment by tpunix** [comment]
[T-31505G  V1.004]
play_delay = 50000

**Comment by box1694** [comment]
not working
