### ISSUE TITLE
Error on In the hunt (US) and (EU) 

### ISSUE THREAD

**Issue by odiaboeeu** [tpunix/SAROO#54]
In the previous version of firmware it gave the same problem, but in this version it doesn't work at all. 

It used to work randomly with 3k play delay and 6k sector delay, although most of the time it doesn't go past the second fmv, but now in version 0.3 it's not working anymore

**Comment by odiaboeeu** [comment]
I didn't know about this bug, I'll test it later. 

I'll leave this issue open in case anyone has the 

Thanks for the info 🙂

**Comment by keeper7keys** [comment]
I just tested it.
It boots with 2nd controller connected and it seems to be working.

**Comment by tzmwx** [comment]
> In the previous version of firmware it gave the same problem, but in this version it doesn't work at all.
> 
> It used to work randomly with 3k play delay and 6k sector delay, although most of the time it doesn't go past the second fmv, but now in version 0.3 it's not working anymore

2种播放选择一种：
1.将系统时间调节到1994年-1999年；
2.主机2P端口插上手柄或鼠标
