### ISSUE TITLE
Gunbird (Japan) - Cutscene is frozen

### ISSUE THREAD

**Issue by keeper7keys** [tpunix/SAROO#56]
FW: 231125 & 0.3
There's no animation during the custscene:
https://youtu.be/XiXB9hAUs0g

How it should looklike:
https://youtu.be/j2oIC1_Xsgw

Best regards

**Comment by odiaboeeu** [comment]
Apparently the version of the firmware they released on the 16th fixed this problem, If you can test again

**Comment by atds55** [comment]
> Aparentemente a versão do firmware que eles lançaram no dia 16 corrigiu esse problema, se puder testar novamente

I tested it here and it didn't fix it, I still have the same problem.

**Comment by odiaboeeu** [comment]
This fixes the problems that animation is only in the first animation, all the levels I played worked as expected animation, if you can test it

*# GUNBIRD
[T-14402G  V1.01J]
play_delay= 65000
sector_delay = 8000

**Comment by atds55** [comment]
> Isso corrige os problemas que a animação fica apenas na primeira animação, todos os níveis que joguei funcionaram como animação esperada, se puder testar
> 
> *#GUNBIRD [T-14402G V1.01J] play_delay = 65000 setor_atraso = 8000
With this configuration Gunbird worked perfectly. 
Thanks for sharing this configuration.

**Comment by Redpad** [comment]
Config setting did not work for me at all. I saw no diference in load times, so I assume its not in effect at all (wrong tittle id or ver?). Tried with a couple different images from different places, all same results.

**Comment by atds55** [comment]
> A configuração não funcionou para mim. Não vi nenhuma diferença nos tempos de carregamento, então presumo que não esteja em vigor (id ou versão do título errado?). Tentei com algumas imagens diferentes de lugares diferentes, todos os mesmos resultados.

You have to observe the number of spaces between the T-14402G and V1.01J, normally it is 2 or 3 spaces. You can try to put 2 or 3 spaces, or open track 1 of the game with a hexadecimal editor and see how many spaces there are in the game image. But you can try 2 if it doesn't work, try 3 spaces.

**Comment by Redpad** [comment]
> > A configuração não funcionou para mim. Não vi nenhuma diferença nos tempos de carregamento, então presumo que não esteja em vigor (id ou versão do título errado?). Tentei com algumas imagens diferentes de lugares diferentes, todos os mesmos resultados.
> 
> You have to observe the number of spaces between the T-14402G and V1.01J, normally it is 2 or 3 spaces. You can try to put 2 or 3 spaces, or open track 1 of the game with a hexadecimal editor and see how many spaces there are in the game image. But you can try 2 if it doesn't work, try 3 spaces.

That did the trick! Good to know there I can find the proper id for future reference. Thanks
