### ISSUE TITLE
设置 Firm_Saturn 的开发环境（菜单

### ISSUE THREAD

**Issue by cyo-the-vile** [tpunix/SAROO#7]
老板，我正在编辑菜单。我把字符串翻译成英文。我们的想法是有一个英文菜单。我下载了 SaturnOrbit，将编译器更改为 SH-ELF，但遇到链接器错误。您有什么建议来修复开发环境吗？我想为这个项目贡献菜单并将其翻译成其他语言。

**Comment by tpunix** [comment]
Multi language support is OK.  See Firm_Saturn/language.c
Please post your translation!
