### ISSUE TITLE
Digital Dance MIX Namie Amuro[GS-9133  V1.003]

### ISSUE THREAD

**Issue by box1694** [tpunix/SAROO#72]
Characters in the dancing scene will not move
music jump loop

**Comment by tzmwx** [comment]
edit saroocfg.txt

play_delay = 50000

**Comment by box1694** [comment]
I tried several files
It's no use

**Comment by tzmwx** [comment]
![IMG_4230](https://github.com/tpunix/SAROO/assets/129564095/7e34e0c7-0cca-47ce-b13b-54634fe2b5e1)

https://github.com/tpunix/SAROO/assets/129564095/ef13f774-b82f-4cb0-97ee-59f52faaead2

**Comment by box1694** [comment]
Uploading VID_20240204_204457.mp4…

**Comment by tzmwx** [comment]
saroo firmware version？

**Comment by box1694** [comment]
firm v0.3
240118

**Comment by odiaboeeu** [comment]
Redump has two versions of this game.

Better would be a pattern for opening an issue

Name of the file and not the compressed file 

saroo firmware version

Sega saturn bios version 

It's which tests were done with delay sector and with play delay

**Comment by box1694** [comment]
HST-3210 3220
V1.01
[saroocfg.txt](https://github.com/tpunix/SAROO/files/14156869/saroocfg.txt)

**Comment by tzmwx** [comment]
> HST-3210 3220 V1.01 [saroocfg.txt](https://github.com/tpunix/SAROO/files/14156869/saroocfg.txt)

[global]
lang_id = 0
exmem_4M

test：
delete exmem_4M

**Comment by box1694** [comment]
Same problem

Digital Dance Mix Vol. 1 - Namie Amuro (Japan) (Rev A) (10M, 12M)
Digital Dance Mix Vol. 1 - Namie Amuro (Japan) (Rev A) (11M)
I also tried CHD to CUE

**Comment by tzmwx** [comment]
Fpga version？

**Comment by box1694** [comment]
![Uploading IMG_20240204_221722.jpg…]()
