### ISSUE TITLE
Time Bokan Series - Bokan to Ippatsu! Doronboo Kanpekiban (Japan)

### ISSUE THREAD

**Issue by keeper7keys** [tpunix/SAROO#74]
FW: 0.3
The game won't proceed after this pig wall is destroyed on the 1st Stage.
The game is not locked up but stays there forever.
https://i.imgur.com/9NNP8mC.jpg

If you play any music on music test option you won't be able to exit. Pressing B button has no effect.
https://i.imgur.com/uanQMez.jpg

Regards

**Comment by tpunix** [comment]
Please add this to cfg file:

# Time Bokan
[T-20607G  V1.003]
play_delay = 2000

**Comment by keeper7keys** [comment]
> Please add this to cfg file:
> # Time Bokan
> 
> [T-20607G V1.003] play_delay = 2000

It's working now.
Thanks!
