### ISSUE TITLE
Is this TaoBao board a trusted one?

### ISSUE THREAD

**Issue by RiccardoPP** [tpunix/SAROO#76]
Hello, I've found this Saroo v1.33Cu  on TaoBao. It contains a lot of "tpunix marks" on board and has a good price compared to Aliexpress. Is this a legitimate board? 

Link: https://item.taobao.com/item.htm?id=765444476281

Thanks.

**Comment by Gery8516** [comment]
Hi, got mine setup today. I drag and dropped some Saroo update from martinx on it and can play games and use sd to save games on memory extension. It is seen by other games such as, SF3 SC1 save will be seen on SF3 bonus disc. 

I tested Panzer Dragoon Saga, SF 3 , Ogre Battle and Shining Holy Arc, all worked well for the 30mins + I played, as well as cutscenes. 

I got mine from ebay. same black pcb. Saroo 1.33Cu
