### ISSUE TITLE
Panzer Dragoon Saga - (E) 

### ISSUE THREAD

**Issue by SW3PO** [tpunix/SAROO#77]
All FMV play incredibly slowly with stutters. Some sound effects play in slow motion during gameplay.

**Comment by Gery8516** [comment]
I have no issues with the game, make sure your console version, PAL/NTSC matches the file if you don't have a Hz switch.

**Comment by SW3PO** [comment]
I have a Hz switch on my PAL system and this is the Europe release I’m playing from. Do you have a link to the image you’re using?

**Comment by Gery8516** [comment]
cdro__mance.
