### ISSUE TITLE
Dragon Force (USA) - Audio/Slowdown issues

### ISSUE THREAD

**Issue by keeper7keys** [tpunix/SAROO#82]
FW: 231125 and 0.3

During the intro the music skips:
https://youtu.be/7Um9yz5iXn8

I notice some slowdowns during gameplay but I couldn't record with my cellphone.
I tested using the following sector delay values but there was no difference.
100, 1000, 4000, 8000, 15000, 30000

Regards

**Comment by williamdsw** [comment]
Recorded gameplay for reference:
www.youtube.com/watch?v=VgehcpWAFEI

**Comment by keeper7keys** [comment]
This game is slow pace and right now I filled the screen with 80 soldiers and didn't notice slowdowns during gameplay.
I think this game is fixed on FW 0.5.
Thanks @tpunix.
