### ISSUE TITLE
Batman Forever - The Arcade Game - Graphical Glitch

### ISSUE THREAD

**Issue by keeper7keys** [tpunix/SAROO#83]
FW: 0.3

The opening scene has graphical glitches.
Tested on american and japanese version of the game.

https://youtu.be/fV3dy3YvXBA

I tested using the following sector delay values but there was no difference.
1000, 4000, 8000, 10000, 11000, 12000, 13000, 14000, 15000, 16000, 20000, 30000

Regards

**Comment by tzmwx** [comment]
sector_delay = 40000

**Comment by keeper7keys** [comment]
Setting the value to 40000 fixes the glitch but causes problems during gameplay probably because the delay is too long.
For example the sprites on screen warps from one place to another or take too long to appear, there are pauses during fights, some animations in the result screen after you beat the level sometimes don't show up and the loading is taking too long.

Thanks

**Comment by tzmwx** [comment]
play_delay= 65000
sector_delay = 8000

**Comment by keeper7keys** [comment]
Thanks.
It's working now.

**Comment by outrunner-2049** [comment]
I tested this on the latest firmware (0.9) and the intro displays correctly without any delays.

**Comment by williamdsw** [comment]
Additional footage of v0.9 firmware running without any config:

[![](https://img.youtube.com/vi/9TyayW9kZCA/0.jpg)](https://www.youtube.com/watch?v=9TyayW9kZCA)

**Comment by keeper7keys** [comment]
This game doesn't need any delays since firmware 0.7:

游戏修正：
修正--Croc - Legend of the Gobbos角色没有头以及部分画面错乱的问题
修正--MARVEL_SUPER某些版本不能运行的问题
修正--Ultimate Mortal Kombat 3会打开光驱驱动器的问题
修正--Batman_Forever_The_Arcade_Game需要超大延迟的问题，现在可以删除cfg里面对此游戏的延迟设置
修正--Game no Tatsujin 2黑屏问题
修正--Pia_Carrot_e_Youkoso_2对加速卡的支持
