### ISSUE TITLE
Compiled Firm_Saturn, Failed to display

### ISSUE THREAD

**Issue by cyo-the-vile** [tpunix/SAROO#9]
I have sent you an email.

I can compile the new firm_saturn files you posted yesterday.  However, the menu is broken. I am on the latest MCU firmware for October.

In main.c, after smpc_cmd(CDOFF) is performed, Saroo never gets to while(1) loop, initializing the menu and shell.
Can you please fix this for the menu? I am ready to push commit for French and Portuguese translation.  However, I cannot get menu to work.

**Comment by cyo-the-vile** [comment]
Please check.

https://drive.google.com/file/d/1_0N2lAvqwcUcjSZA00vC0i3J7Tfk2_nN/view?usp=drivesdk

**Comment by tpunix** [comment]
Please move "smpc_cmd" before "pad_init" and test it again

**Comment by cyo-the-vile** [comment]
`int _main(void)
{
	conio_init();
	smpc_cmd(CDOFF);
	pad_init();

	printk("    SRAOOO start!\n");

	mcu_ver = LE32((void*)(SYSINFO_ADDR+0x00));
	lang_id = LE32((void*)(SYSINFO_ADDR+0x04));


	// restore bios_loadcd_init1
	*(u32*)(0x060002dc) = 0x2650;

	//ASR0 = 0x31101f00;
	//AREF = 0x00000013;

	sci_init();
	printk("\n\nSAROOO Serial Monitor Start!\n");
	printk("   MCU ver: %08x\n", mcu_ver);
	printk("    SS ver: %08x\n", get_build_date());
	printk("  FPGA ver: %08x\n", SS_VER);
	printk("   lang_id: %d\n", lang_id);

	// CDBlock Off
//	smpc_cmd(CDOFF);`

It won't show the menu still.

It is now displaying the following on Saturn:
SMC_CMD(09) ...
done. SS=c0
SRAOOO start!

**Comment by tpunix** [comment]
Please comment sci_init and try

**Comment by cyo-the-vile** [comment]
In Yabuse emulator, it boots to Chinese menu still.  However, I recall on Saroo, was having the problems. Just like the photograph.

I will test it when I get home.

**Comment by cyo-the-vile** [comment]
Display says:
Lang_id: -1631327553

Menu does not load.


My lang_id in Language.c is set to "1" 

https://imgur.com/gallery/5CkfwlS

**Comment by cyo-the-vile** [comment]
lang_init function appears to not be able to switch between CH and ENG.  Saroo hangs when this function runs in main.c

I am suspecting the logic inside `void lang_init(void)` inside language.c is not working properly

**Comment by cyo-the-vile** [comment]
I was mistaken;

`//	lang_id = LE32((void*)(0));` must be comment in main.c
`sci_init();` must be comment in main.c 

if it is not comment, Saroo does not start.

How to change the default language to English?

**Comment by tpunix** [comment]
lang_id can be set at saroocfg.txt:
[global]
lang_id = 0
0 for zhcn, 1 for eng

**Comment by cyo-the-vile** [comment]
Thank you boss.
